// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@interface NSError (XCTAutomationSupportErrors)
+ (id)_xctas_error:(NSInteger)arg1 description:(id)arg2;
+ (id)_xctas_error:(NSInteger)arg1 userInfo:(id)arg2 description:(id)arg3;
+ (id)_xctas_error:(NSInteger)arg1 userInfo:(id)arg2 description:(id)arg3 arguments:(char *)arg4;
@end

