// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSData;

@interface XCAccessibilityElement : NSObject <NSCopying, NSSecureCoding>
{
    NSInteger _processIdentifier;
    struct __AXUIElement *_AXUIElement;
    NSUInteger _elementType;
    NSUInteger _originPlatform;
    NSData *_token;
    NSUInteger _elementOrHash;
    NSUInteger _elementID;
}

@property(readonly) struct __AXUIElement *AXUIElement;
@property(readonly) NSUInteger elementID;
@property(readonly) NSUInteger elementOrHash;
@property(readonly) NSUInteger elementType;
@property(readonly) BOOL hasValidElementType;
@property(readonly) NSUInteger originPlatform;
@property(readonly) NSInteger processIdentifier;
@property(readonly, copy) NSData *token;

+ (id)deviceElement;
+ (id)elementWithAXUIElement:(struct __AXUIElement *)arg1;
+ (id)elementWithProcessIdentifier:(NSInteger)arg1;
+ (id)elementWithProcessIdentifier:(NSInteger)arg1 originPlatform:(NSUInteger)arg2;
+ (id)mockElementWithProcessIdentifier:(NSInteger)arg1;
+ (id)mockElementWithProcessIdentifier:(NSInteger)arg1 originPlatform:(NSUInteger)arg2;
+ (id)mockElementWithProcessIdentifier:(NSInteger)arg1 originPlatform:(NSUInteger)arg2 payload:(id)arg3;
+ (id)mockElementWithProcessIdentifier:(NSInteger)arg1 payload:(id)arg2;
+ (id)mockInvalidElementWithProcessIdentifier:(NSInteger)arg1;
+ (id)mockInvalidElementWithProcessIdentifier:(NSInteger)arg1 originPlatform:(NSUInteger)arg2;
+ (id)mockInvalidElementWithProcessIdentifier:(NSInteger)arg1 originPlatform:(NSUInteger)arg2 payload:(id)arg3;
- (id)initWithAXUIElement:(struct __AXUIElement *)arg1 elementType:(NSUInteger)arg2 originPlatform:(NSUInteger)arg3;
- (id)initWithToken:(id)arg1 elementOrHash:(NSUInteger)arg2 elementID:(NSUInteger)arg3 pid:(NSInteger)arg4 elementType:(NSUInteger)arg5 originPlatform:(NSUInteger)arg6;

@end

