// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@interface XCDeviceEvent : NSObject <NSSecureCoding>
{
    NSUInteger _eventPage;
    NSUInteger _usage;
    double _duration;
    NSUInteger _type;
    double _rotation;
}

@property double duration;
@property NSUInteger eventPage;
@property(readonly) BOOL isButtonHoldEvent;
@property double rotation;
@property NSUInteger type;
@property NSUInteger usage;

+ (id)deviceEventForDigitalCrownRotation:(double)arg1 velocity:(double)arg2;
+ (id)deviceEventWithPage:(NSUInteger)arg1 usage:(NSUInteger)arg2 duration:(double)arg3;

@end

