// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>



@interface XCTApplicationStateSnapshot : NSObject <NSSecureCoding>
{
    NSInteger _processID;
    NSInteger _bridgedProcessID;
    NSString *_bundleID;
    NSString *_path;
    NSUInteger _runState;
    NSUInteger _activationPolicy;
    NSUInteger _eventID;
}

@property(readonly) NSUInteger activationPolicy;
@property(readonly) NSInteger bridgedProcessID;
@property(readonly, copy) NSString *bundleID;
@property(readonly) NSUInteger eventID;
@property(readonly, copy) NSString *path;
@property(readonly) NSInteger processID;
@property(readonly) NSUInteger runState;

- (id)initWithBundleID:(id)arg1 path:(id)arg2 runState:(NSUInteger)arg3 processID:(NSInteger)arg4 activationPolicy:(NSUInteger)arg5 eventID:(NSUInteger)arg6;
- (id)initWithBundleID:(id)arg1 path:(id)arg2 runState:(NSUInteger)arg3 processID:(NSInteger)arg4 bridgedProcessID:(NSInteger)arg5 activationPolicy:(NSUInteger)arg6 eventID:(NSUInteger)arg7;

@end

