// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSArray, NSDictionary, XCAccessibilityElement;

@protocol XCTAccessibilityFramework <NSObject>
- (NSInteger)appOrientationForElement:(const struct __AXUIElement *)arg1 error:(id *)arg2;
- (NSArray *)attributes:(NSArray *)arg1 forElement:(const struct __AXUIElement *)arg2 error:(id *)arg3;
- (NSDictionary *)attributesForElement:(XCAccessibilityElement *)arg1 attributes:(NSArray *)arg2 error:(id *)arg3;
- (CGRect)frameForElement:(const struct __AXUIElement *)arg1 error:(id *)arg2;
- (const struct __AXUIElement *)mainWindowForElement:(const struct __AXUIElement *)arg1 error:(id *)arg2;
- (void)performWithAXTimeout:(double)arg1 block:(void (^)(void))arg2;
- (NSDictionary *)userTestingSnapshotForElement:(const struct __AXUIElement *)arg1 options:(NSDictionary *)arg2 error:(id *)arg3;
@end

