// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTAccessibilityFramework-Protocol.h"


@interface XCTAccessibilityFramework : NSObject <XCTAccessibilityFramework>
{
    BOOL _allowsRemoteAccess;
    struct __AXUIElement *_systemWideElement;
}

@property BOOL allowsRemoteAccess;
@property struct __AXUIElement *systemWideElement;

+ (void)_startAXServer;
- (NSInteger)appOrientationForElement:(struct __AXUIElement *)arg1 error:(id *)arg2;
- (id)attributes:(id)arg1 forElement:(struct __AXUIElement *)arg2 error:(id *)arg3;
- (CGRect)frameForElement:(struct __AXUIElement *)arg1 error:(id *)arg2;
- (const struct __AXUIElement *)mainWindowForElement:(struct __AXUIElement *)arg1 error:(id *)arg2;
- (void)performWithAXTimeout:(double)arg1 block:(CDUnknownBlockType)arg2;
- (id)userTestingSnapshotForElement:(struct __AXUIElement *)arg1 options:(id)arg2 error:(id *)arg3;


@end

