// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2018 09:07:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTAutomationTarget-Protocol.h"
#import "XCTConnectionAccepting-Protocol.h"

@class NSMutableArray, NSString, XCTAnimationsIdleNotifier, XCTElementQueryProcessor, XCTMainRunLoopIdleNotifier;
@protocol OS_dispatch_queue;

@interface XCTAutomationSession : NSObject <XCTConnectionAccepting, XCTAutomationTarget>
{
    NSMutableArray *_connections;
    XCTElementQueryProcessor *_queryProcessor;
    NSObject<OS_dispatch_queue> *_queue;
    XCTMainRunLoopIdleNotifier *_runLoopIdleMonitor;
    XCTAnimationsIdleNotifier *_animationIdleNotifier;
}

@property(readonly) XCTAnimationsIdleNotifier *animationIdleNotifier;
@property(readonly) NSMutableArray *connections;
@property(readonly) XCTElementQueryProcessor *queryProcessor;
@property(readonly) NSObject<OS_dispatch_queue> *queue;
@property(readonly) XCTMainRunLoopIdleNotifier *runLoopIdleMonitor;

- (BOOL)acceptNewConnection:(id)arg1;
- (void)attributesForElement:(id)arg1 attributes:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)fetchMatchesForQuery:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)notifyWhenAnimationsAreIdle:(CDUnknownBlockType)arg1;
- (void)notifyWhenMainRunLoopIsIdle:(CDUnknownBlockType)arg1;
- (void)requestHostAppExecutableNameWithReply:(CDUnknownBlockType)arg1;


@end

