// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTCapabilitiesProviding.h"


@interface XCTAnimationsIdleNotifier : NSObject <XCTCapabilitiesProviding>
{
}

+ (void)addAnimationIdleHandler:(CDUnknownBlockType)arg1;
+ (void)animationDidStart;
+ (void)animationDidStop;
+ (void)handleAnimationsIdle;
+ (BOOL)isAnimationInProgress;
+ (void)provideCapabilitiesToBuilder:(id)arg1;
+ (BOOL)supportsAnimationsIdleNotification;
+ (BOOL)swizzleUIViewAnimationStateMethodsWithError:(id *)arg1;
- (void)notifyWhenIdle:(CDUnknownBlockType)arg1;


@end

