// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface XCTAccessibilitySnapshot_iOS : NSObject <NSCopying>
{
    NSDictionary *_userTestingSnapshot;
    NSDictionary *_snapshotOptions;
    struct __AXUIElement *_mainWindowRef;
    NSInteger _appOrientation;
    CGRect _mainWindowFrame;
}

@property(readonly) NSInteger appOrientation;
@property(readonly) CGRect mainWindowFrame;
@property(readonly) struct __AXUIElement *mainWindowRef;
@property(readonly) NSDictionary *snapshotOptions;
@property(readonly) NSDictionary *userTestingSnapshot;

- (id)initWithUserTestingSnapshot:(id)arg1 snapshotOptions:(id)arg2 mainWindowRef:(struct __AXUIElement *)arg3 mainWindowFrame:(CGRect)arg4 appOrientation:(NSInteger)arg5;

@end

