// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSDictionary;

@interface XCTCapabilities : NSObject <NSSecureCoding>
{
    NSDictionary *_capabilitiesDictionary;
}

@property(readonly, copy) NSDictionary *capabilitiesDictionary;
@property(readonly, copy) NSDictionary *dictionaryRepresentation;

+ (id)emptyCapabilities;
- (BOOL)hasCapability:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (NSUInteger)versionForCapability:(id)arg1;

@end

