// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTMatchingElementIterator.h"

@class XCTElementContainingTransformer;

__attribute__((visibility("hidden")))
@interface XCTContainingTransformerIterator : XCTMatchingElementIterator
{
    BOOL _hasCheckedInput;
    XCTElementContainingTransformer *_containingTransformer;
}

@property(readonly) XCTElementContainingTransformer *containingTransformer;

- (id)initWithInput:(id)arg1 containingTransformer:(id)arg2;
- (id)nextMatch;

@end

