// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTCapabilitiesProviding.h"
#import "XCTRuntimeIssueContextReportingDelegate.h"

@class NSOrderedSet, NSSet, NSString, XCElementSnapshot;

@interface XCTElementQueryResults : NSObject <NSSecureCoding, XCTCapabilitiesProviding, XCTRuntimeIssueContextReportingDelegate>
{
    XCElementSnapshot *_rootElement;
    NSOrderedSet *_matchingElements;
    NSSet *_remoteElements;
    NSOrderedSet *_runtimeIssues;
    NSString *_noMatchesMessage;
}

@property(readonly, copy) NSOrderedSet *matchingElements;
@property(readonly, copy) NSString *noMatchesMessage;
@property(readonly, copy) NSSet *remoteElements;
@property(readonly) XCElementSnapshot *rootElement;
@property(readonly, copy) NSOrderedSet *runtimeIssues;

+ (void)provideCapabilitiesToBuilder:(id)arg1;
+ (BOOL)shouldRuntimeIssueContext:(id)arg1 reportIssue:(id)arg2;
- (id)initWithRootElement:(id)arg1 matchingElements:(id)arg2 remoteElements:(id)arg3 runtimeIssues:(id)arg4 noMatchesMessage:(id)arg5;
- (id)resultsByReplacingRuntimeIssues:(id)arg1;


@end

