// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSArray, XCAccessibilityElement, XCElementSnapshot;


@protocol XCTElementSnapshotProvider;
@protocol XCTElementSnapshotAttributeDataSource;

@interface XCTElementQuery : NSObject <NSSecureCoding>
{
    BOOL _suppressAttributeKeyPathAnalysis;
    id <XCTElementSnapshotProvider> _snapshotProvider;
    id <XCTElementSnapshotAttributeDataSource> _elementSnapshotAttributeDataSource;
    NSUInteger _options;
    XCElementSnapshot *_rootElementSnapshot;
    CDUnknownBlockType _evaluationContext;
    double _responsivenessTimeout;
    double _executionTimeout;
    XCAccessibilityElement *_rootElement;
    NSArray *_transformers;
}

@property __weak id <XCTElementSnapshotAttributeDataSource> elementSnapshotAttributeDataSource;
@property(copy, nonatomic) CDUnknownBlockType evaluationContext;
@property double executionTimeout;
@property(readonly) NSUInteger options;
@property double responsivenessTimeout;
@property(readonly, copy) XCAccessibilityElement *rootElement;
@property(retain) XCElementSnapshot *rootElementSnapshot;
@property(retain) id <XCTElementSnapshotProvider> snapshotProvider;
@property BOOL suppressAttributeKeyPathAnalysis;
@property(readonly) BOOL supportsAttributeKeyPathAnalysis;
@property(readonly) BOOL supportsRemoteEvaluation;
@property(readonly, copy) NSArray *transformers;

+ (id)_firstMatchTransformerSubarraysFromArray:(id)arg1 trailingMatchAllTransformers:(id *)arg2;
- (id)_allMatchingSnapshotsForInput:(id)arg1 transformers:(id)arg2 relatedElements:(id *)arg3 error:(id *)arg4;
- (id)_firstMatchingSnapshotForInput:(id)arg1 transformers:(id)arg2 relatedElements:(id *)arg3 error:(id *)arg4;
- (id)_firstMatchingSnapshotForInput:(id)arg1 transformersSubarrays:(id)arg2 relatedElements:(id *)arg3 error:(id *)arg4;
- (id)_rootElementSnapshot:(id *)arg1;
- (id)_snapshotAttributesOrError:(id *)arg1;
- (id)_snapshotForElement:(id)arg1 error:(id *)arg2;
- (BOOL)hasTransformerWithStopsOnFirstMatch;
- (id)initWithRootElement:(id)arg1 transformers:(id)arg2;
- (id)initWithRootElement:(id)arg1 transformers:(id)arg2 options:(NSUInteger)arg3;
- (id)matchingSnapshotsWithError:(id *)arg1;
- (id)matchingSnapshotsWithRelatedElements:(id *)arg1 error:(id *)arg2;

@end

