// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTElementSnapshotAttributeDataSource-Protocol.h"
#import "XCTElementSnapshotProvider-Protocol.h"

@class NSString, XCTCapabilities;
@protocol XCTElementSnapshotProvider;


@protocol XCTElementSnapshotProvider;

@interface XCTElementQueryProcessor : NSObject <XCTElementSnapshotProvider, XCTElementSnapshotAttributeDataSource>
{
    id <XCTElementSnapshotProvider> _snapshotProvider;
    XCTCapabilities *_remoteInterfaceCapabilities;
}

@property(readonly) BOOL allowsRemoteAccess;
@property(retain) XCTCapabilities *remoteInterfaceCapabilities;
@property __weak id <XCTElementSnapshotProvider> snapshotProvider;
@property(readonly) BOOL supportsHostedViewCoordinateTransformations;
@property(readonly) BOOL usePointTransformationsForFrameConversions;

- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (void)fetchMatchesForQuery:(id)arg1 clientCapabilities:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (id)parameterizedAttribute:(id)arg1 forElement:(id)arg2 parameter:(id)arg3 error:(id *)arg4;
- (id)snapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 timeoutControls:(id)arg4 error:(id *)arg5;


@end

