// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSPredicate;

@interface XCTElementFilteringTransformer
{
    NSInteger _scope;
    NSPredicate *_predicate;
}

@property(readonly, copy) NSPredicate *predicate;
@property(readonly) NSInteger scope;

- (id)_scopedExpansionOfInput:(id)arg1;
- (BOOL)canBeRemotelyEvaluatedWithCapabilities:(id)arg1;
- (id)elementTypes;
- (id)initWithScope:(NSInteger)arg1 predicate:(id)arg2;
- (id)iteratorForInput:(id)arg1;
- (id)requiredKeyPathsOrError:(id *)arg1;
- (BOOL)supportsAttributeKeyPathAnalysis;
- (id)transform:(id)arg1 relatedElements:(id *)arg2;

@end

