// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTElementSnapshotAttributeDataSource-Protocol.h"
#import "XCTElementSnapshotProvider-Protocol.h"



@protocol XCTElementSnapshotProvider;

@interface XCTElementQueryProcessor : NSObject <XCTElementSnapshotProvider, XCTElementSnapshotAttributeDataSource>
{
    id <XCTElementSnapshotProvider> _snapshotProvider;
}

@property __weak id <XCTElementSnapshotProvider> snapshotProvider;

- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (void)fetchMatchesForQuery:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (id)snapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 error:(id *)arg4;


@end

