// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSMutableArray;

@interface XCTMainRunLoopIdleNotifier : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_idleHandlers;
    struct __CFRunLoopObserver *_runLoopObserver;
}

@property(readonly) NSMutableArray *idleHandlers;
@property(readonly) NSObject<OS_dispatch_queue> *queue;
@property struct __CFRunLoopObserver *runLoopObserver;

- (void)_queue_setUpRunLoopObserver;
- (void)handleIdleObserved;
- (void)notifyWhenIdle:(CDUnknownBlockType)arg1;

@end

