// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSArray, XCAccessibilityElement, XCTElementQuery;

@protocol XCTRemoteApplicationAutomationTarget
- (id)_XCT_attributesForElement:(XCAccessibilityElement *)arg1 attributes:(NSArray *)arg2;
- (id)_XCT_fetchMatchesForQuery:(XCTElementQuery *)arg1;
- (id)_XCT_notifyWhenAnimationsAreIdle;
- (id)_XCT_notifyWhenMainRunLoopIsIdle;
@end

