// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSString, XCTSignpostEvent;

@interface XCTSignpostInterval : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_subsystem;
    NSString *_category;
    NSString *_name;
    XCTSignpostEvent *_beginEvent;
    XCTSignpostEvent *_endEvent;
}

@property(readonly, copy, nonatomic) XCTSignpostEvent *beginEvent;
@property(readonly, copy, nonatomic) NSString *category;
@property(readonly, copy, nonatomic) XCTSignpostEvent *endEvent;
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSString *subsystem;

- (id)initWithSignpostInterval:(id)arg1;
- (id)initWithSubsystem:(id)arg1 category:(id)arg2 name:(id)arg3 beginEvent:(id)arg4 endEvent:(id)arg5;

@end

