// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class XCTImageEncoding;

@interface XCTScreenshotRequest : NSObject <NSSecureCoding>
{
    NSInteger _screenID;
    XCTImageEncoding *_encoding;
    NSUInteger _options;
    CGRect _rect;
}

@property(readonly) XCTImageEncoding *encoding;
@property(readonly) NSUInteger options;
@property(readonly) CGRect rect;
@property(readonly) NSInteger screenID;

- (id)initWithScreenID:(NSInteger)arg1 rect:(CGRect)arg2 encoding:(id)arg3;
- (id)initWithScreenID:(NSInteger)arg1 rect:(CGRect)arg2 encoding:(id)arg3 options:(NSUInteger)arg4;

@end

