// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@interface XCTTimeoutControls : NSObject <NSSecureCoding>
{
    double _mainThreadResponsivenessTimeout;
    double _queryExecutionTimeout;
}

@property double mainThreadResponsivenessTimeout;
@property double queryExecutionTimeout;

+ (double)defaultMainThreadReponsivenessTimeout;
+ (double)defaultQueryExecutionTimeout;
+ (void)setDefaultMainThreadReponsivenessTimeout:(double)arg1;
+ (void)setDefaultQueryExecutionTimeout:(double)arg1;
+ (id)standardTimeoutControls;

@end

