// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSDate, NSString;

@interface XCTTailspinRequest : NSObject <NSSecureCoding>
{
    BOOL _collectOSLogs;
    BOOL _collectOSSignposts;
    BOOL _redactSensitiveInformation;
    NSInteger _processID;
    NSDate *_startDate;
    NSString *_reason;
    NSString *_fileName;
}

@property(readonly, nonatomic) BOOL collectOSLogs;
@property(readonly, nonatomic) BOOL collectOSSignposts;
@property(readonly, copy, nonatomic) NSString *fileName;
@property(readonly, nonatomic) NSInteger processID;
@property(readonly, copy, nonatomic) NSString *reason;
@property(readonly, nonatomic) BOOL redactSensitiveInformation;
@property(readonly, copy, nonatomic) NSDate *startDate;

- (id)initWithProcessID:(NSInteger)arg1 collectOSLogs:(BOOL)arg2 collectOSSignposts:(BOOL)arg3 redactSensitiveInformation:(BOOL)arg4 startDate:(id)arg5 reason:(id)arg6 fileName:(id)arg7;

@end

