// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCUICapabilities-Protocol.h"

@class NSDictionary, NSString;
@protocol XCUICapabilities;

@interface XCUICapabilities : NSObject <XCUICapabilities>
{
}

@property(readonly) NSInteger automationSessionSupport;
@property(readonly) BOOL automationSessionSupportsAnimationsIdleNotifications;
@property(readonly) BOOL automationSessionSupportsAttributeFetching;
@property(readonly) BOOL automationSessionSupportsMainRunLoopIdleNotifications;
@property(readonly) id <XCUICapabilities> bridgedProcessCapabilities;
@property(readonly) BOOL supportsTruncatedValue;
@property(readonly) NSString *truncatedValueAttribute;
@property(readonly) NSDictionary *truncatedValueSnapshotParameter;

- (BOOL)_supportsFeature:(id)arg1 requiresMacOS:(NSInteger)arg2 iOS:(NSInteger)arg3 tvOS:(NSInteger)arg4 watchOS:(NSInteger)arg5;
- (BOOL)_supportsFeature:(id)arg1 requiresMacOS:(NSInteger)arg2 macOSBuildNumber:(NSInteger)arg3 iOS:(NSInteger)arg4 iOSBuildNumber:(NSInteger)arg5 tvOS:(NSInteger)arg6 tvOSBuildNumber:(NSInteger)arg7 watchOS:(NSInteger)arg8 watchOSBuildNumber:(NSInteger)arg9;


@end

