// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTCapabilitiesProviding-Protocol.h"
#import "XCTRuntimeIssueContextReportingDelegate-Protocol.h"

@class NSOrderedSet, NSString, XCElementSnapshot;

@interface XCUIElementSnapshotRequestResult : NSObject <NSSecureCoding, XCTCapabilitiesProviding, XCTRuntimeIssueContextReportingDelegate>
{
    XCElementSnapshot *_rootElementSnapshot;
    NSOrderedSet *_runtimeIssues;
}

@property(readonly) XCElementSnapshot *rootElementSnapshot;
@property(readonly, copy) NSOrderedSet *runtimeIssues;

+ (void)provideCapabilitiesToBuilder:(id)arg1;
+ (BOOL)shouldRuntimeIssueContext:(id)arg1 reportIssue:(id)arg2;
- (id)initWithRootElementSnapshot:(id)arg1 runtimeIssues:(id)arg2;


@end

