// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@interface DTXBlockCompressorLibCompression : NSObject
{
    _Atomic NSUInteger _lzfseScratchBuffer;
    _Atomic NSUInteger _lz4ScratchBuffer;
}

- (NSUInteger)compressBuffer:(const char *)arg1 ofLength:(NSUInteger)arg2 toBuffer:(char *)arg3 ofLength:(NSUInteger)arg4 usingCompressionType:(NSInteger)arg5 withFinalCompressionType:(NSInteger *)arg6;
- (BOOL)uncompressBuffer:(const char *)arg1 ofLength:(NSUInteger)arg2 toBuffer:(char *)arg3 withKnownUncompressedLength:(NSUInteger)arg4 usingCompressionType:(NSInteger)arg5;


@end

