// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <DTXConnectionServices/DTXAllowedRPC-Protocol.h>

@class NSDictionary, NSString;

@protocol DTXConnectionRemoteReceiveQueueCalls <DTXAllowedRPC>
- (void)_channelCanceled:(NSUInteger)arg1;
- (void)_notifyCompressionHint:(NSUInteger)arg1 forChannelCode:(NSUInteger)arg2;
- (void)_notifyOfPublishedCapabilities:(NSDictionary *)arg1;
- (void)_requestChannelWithCode:(NSUInteger)arg1 identifier:(NSString *)arg2;
- (void)_setTracerState:(NSUInteger)arg1;
@end

