// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSObject;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface DTXFileDescriptorTransport
{
    NSInteger _inFD;
    NSInteger _outFD;
    NSObject<OS_dispatch_queue> *_inputQueue;
    NSObject<OS_dispatch_queue> *_outputQueue;
    NSInteger _outputWaitKQ;
    NSObject<OS_dispatch_source> *_inputSource;
    CDUnknownBlockType _inputReaderBlock;
    CDUnknownBlockType _disconnectBlock;
}

- (NSInteger)_createWriteKQueue:(NSInteger)arg1;
- (void)_setupReadSource:(NSInteger)arg1;
- (void)disconnect;
- (id)initWithIncomingFileDescriptor:(NSInteger)arg1 outgoingFileDescriptor:(NSInteger)arg2 disconnectBlock:(CDUnknownBlockType)arg3;
- (id)initWithIncomingFilePath:(id)arg1 outgoingFilePath:(id)arg2 error:(id *)arg3;
- (id)initWithXPCRepresentation:(id)arg1;
- (id)serializedXPCRepresentation;
- (void)setupWithIncomingDescriptor:(NSInteger)arg1 outgoingDescriptor:(NSInteger)arg2 disconnectBlock:(CDUnknownBlockType)arg3;
- (NSUInteger)supportedDirections;
- (NSUInteger)transmit:(const void *)arg1 ofLength:(NSUInteger)arg2;

@end

