// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol DTXBlockCompressor, OS_dispatch_queue;

@interface DTXMessageParser : NSObject
{
    const char *_parsingBuffer;
    NSUInteger _parsingBufferUsed;
    NSUInteger _parsingBufferSize;
    CDUnknownBlockType _exceptionHandler;
    CDUnknownBlockType _parsedMessageHandler;
    BOOL _eof;
    NSObject<OS_dispatch_queue> *_parsingQueue;
    NSMutableDictionary *_fragmentedBuffersByIdentifier;
    id <DTXBlockCompressor> _compressor;
}

- (void)_messageParsedWithHeader:(struct DTXMessageHeader)arg1 bytes:(const void *)arg2 length:(NSUInteger)arg3 destructor:(CDUnknownBlockType)arg4;
- (id)initWithMessageHandler:(CDUnknownBlockType)arg1 andParseExceptionHandler:(CDUnknownBlockType)arg2;
- (void)parseIncomingBytes:(const char *)arg1 length:(NSUInteger)arg2;
- (id)parsingComplete;
- (void)replaceCompressor:(id)arg1;

@end

