// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class DTXChannel, NSSet, Protocol;

@interface DTXProxyChannel : NSObject
{
    Protocol *_remoteInterface;
    Protocol *_exportedInterface;
    DTXChannel *_channel;
    NSSet *_additionalAllowedClassesForProtocolMethods;
    _Atomic BOOL _hasProcessedMessage;
}

@property(retain, nonatomic) NSSet *additionalAllowedClassesForProtocolMethods;
@property(retain, nonatomic) DTXChannel *channel;
@property(retain) Protocol *remoteInterface;
@property(readonly) id remoteObjectProxy;

- (id)_allowedClassesForArgumentsOfRemoteInterfaceSelector:(SEL)arg1 methodSignature:(id)arg2;
- (id)_allowedClassesForReturnValues;
- (void)_sendInvocationMessage:(id)arg1;
- (id)_validateDispatch:(id)arg1;
- (void)cancel;
- (id)initWithChannel:(id)arg1 remoteProtocol:(id)arg2 localProtocol:(id)arg3;
- (void)setExportedObject:(id)arg1 queue:(id)arg2;

@end

