// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@interface DTXRemoteInvocationReceipt : NSObject
{
    id _returnValue;
    CDUnknownBlockType _completionHandler;
    CDUnknownBlockType _waiterChain;
    struct os_unfair_lock_s _guard;
    NSUInteger _valueState:2;
    NSUInteger _completionState:2;
    NSUInteger _reserved:28;
}

- (void)_checkedAssign:(CDUnknownBlockType)arg1;
- (void)handleCompletion:(CDUnknownBlockType)arg1;
- (void)invokeCompletionWithReturnValue:(id)arg1 error:(id)arg2;
- (void)waitForFulfillment;

@end

