// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSArray, NSObject;
@protocol OS_dispatch_semaphore;

@interface DTXSocketTransport
{
    NSObject<OS_dispatch_semaphore> *_socketAcceptedSem;
    _Atomic NSInteger _socketSemProtector;
    NSArray *_addresses;
    NSInteger _port;
}

@property(readonly) NSInteger port;

+ (id)addressForHost:(const char *)arg1 port:(NSInteger)arg2;
+ (id)schemes;
- (void)_commonSocketTransportInit;
- (void)_setupChannelWithConnectedSocket:(NSInteger)arg1 assumingOwnership:(BOOL)arg2 orDisconnectBlock:(CDUnknownBlockType)arg3;
- (void)_setupWithLocalPort:(NSInteger)arg1;
- (void)_signalSocketAccepted;
- (void)disconnect;
- (id)initWithConnectedSocket:(NSInteger)arg1 disconnectAction:(CDUnknownBlockType)arg2;
- (id)initWithLocalPort:(NSInteger)arg1;
- (id)initWithRemoteAddress:(id)arg1;
- (id)localAddresses;
- (NSUInteger)supportedDirections;
- (NSUInteger)transmit:(const void *)arg1 ofLength:(NSUInteger)arg2;

@end

