// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, XCTWaiterManager;
@protocol OS_dispatch_queue, XCTWaiterDelegate;


@protocol XCTWaiterDelegate;

@interface _XCTWaiterImpl : NSObject
{
    id <XCTWaiterDelegate> _delegate;
    XCTWaiterManager *_manager;
    NSArray *_waitCallStackReturnAddresses;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    NSArray *_expectations;
    NSMutableArray *_fulfilledExpectations;
    struct __CFRunLoop *_waitingRunLoop;
    NSInteger _state;
    double _timeout;
    NSInteger _result;
    BOOL _enforceOrderOfFulfillment;
}

@property id <XCTWaiterDelegate> delegate;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *delegateQueue;
@property BOOL enforceOrderOfFulfillment;
@property(copy, nonatomic) NSArray *expectations;
@property(readonly, nonatomic) NSMutableArray *fulfilledExpectations;
@property XCTWaiterManager *manager;
@property NSInteger result;
@property NSInteger state;
@property double timeout;
@property(copy) NSArray *waitCallStackReturnAddresses;
@property struct __CFRunLoop *waitingRunLoop;


@end

