// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTest.h"

@class NSMutableArray, NSMutableDictionary, NSString, XCTestConfiguration;

@interface _XCTestSuiteImplementation : XCTest
{
    NSString *_name;
    NSMutableArray *_tests;
    XCTestConfiguration *_testConfiguration;
    NSMutableDictionary *_activityAggregateStatistics;
}

@property(readonly) NSMutableDictionary *activityAggregateStatistics;
@property(copy) NSString *name;
@property(retain) XCTestConfiguration *testConfiguration;
@property(retain) NSMutableArray *tests;

- (id)initWithName:(id)arg1;

@end

