// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSArray;

@interface _XCTCompoundExpectationImplementation : NSObject
{
    NSUInteger _logicalType;
    NSArray *_subexpectations;
}

@property(readonly, nonatomic) NSUInteger logicalType;
@property(readonly, copy, nonatomic) NSArray *subexpectations;

- (void)cleanup;
- (id)initWithLogicalType:(NSUInteger)arg1 subexpectations:(id)arg2;

@end

