// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, XCTDarwinNotificationExpectation;

@interface _XCTDarwinNotificationExpectationImplementation : NSObject
{
    XCTDarwinNotificationExpectation *_expectation;
    NSString *_notificationName;
    NSInteger _notifyToken;
    CDUnknownBlockType _handler;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _hasCleanedUp;
}

@property(copy) CDUnknownBlockType handler;
@property(readonly, copy) NSString *notificationName;

- (void)_handleNotification;
- (void)cleanup;
- (id)initWithNotificationName:(id)arg1 expectation:(id)arg2;

@end

