// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCUIAccessibilityInterface-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_queue, XCUIApplicationProcessTracker, XCUIRemoteAccessibilityInterface;


@protocol XCUIApplicationProcessTracker;

@interface XCAXClient_iOS : NSObject <XCUIAccessibilityInterface>
{
    id <XCUIApplicationProcessTracker> _applicationProcessTracker;
    id <XCUIRemoteAccessibilityInterface> _remoteAccessibilityInterface;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_userTestingNotificationHandlers;
    NSMutableDictionary *_cachedAccessibilityLoadedValuesForPIDs;
}

@property double AXTimeout;
@property(readonly) BOOL allowsRemoteAccess;
@property(readonly) id <XCUIApplicationProcessTracker> applicationProcessTracker;
@property(readonly) BOOL axNotificationsIncludeElement;
@property(retain) NSMutableDictionary *cachedAccessibilityLoadedValuesForPIDs;
@property(retain) NSObject<OS_dispatch_queue> *queue;
@property(readonly) id <XCUIRemoteAccessibilityInterface> remoteAccessibilityInterface;
@property(retain) NSMutableDictionary *userTestingNotificationHandlers;
@property(readonly) BOOL supportsAnimationsInactiveNotifications;
@property(readonly) BOOL supportsHostedViewCoordinateTransformations;
@property(readonly) BOOL usePointTransformationsForFrameConversions;

- (BOOL)_loadAccessibility:(id *)arg1;
- (BOOL)_registerForAXNotification:(NSInteger)arg1 error:(id *)arg2;
- (BOOL)_setAXTimeout:(double)arg1 error:(id *)arg2;
- (id)accessibilityElementForElementAtPoint:(CGPoint)arg1 error:(id *)arg2;
- (id)activeApplications;
- (id)addObserverForAXNotification:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (BOOL)cachedAccessibilityLoadedValueForPID:(NSInteger)arg1;
- (id)defaultParameters;
- (BOOL)enableFauxCollectionViewCells:(id *)arg1;
- (void)handleAccessibilityNotification:(NSInteger)arg1 fromElement:(id)arg2 payload:(id)arg3;
- (void)handleUserTestingNotification:(id)arg1;
- (id)hitTestElement:(id)arg1 withPoint:(CGPoint)arg2 error:(id *)arg3;
- (id)initWithApplicationProcessTracker:(id)arg1 remoteAccessibilityInterface:(id)arg2;
- (id)interruptingUIElementsAffectingSnapshot:(id)arg1;
- (BOOL)loadAccessibility:(id *)arg1;
- (id)localizableStringsDataForActiveApplications;
- (void)notifyOnNextOccurrenceOfUserTestingEvent:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)notifyWhenEventLoopIsIdleForApplication:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)notifyWhenNoAnimationsAreActiveForApplication:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)notifyWhenViewControllerViewDidAppearReply:(CDUnknownBlockType)arg1;
- (void)notifyWhenViewControllerViewDidDisappearReply:(CDUnknownBlockType)arg1;
- (id)parameterizedAttribute:(id)arg1 forElement:(id)arg2 parameter:(id)arg3 error:(id *)arg4;
- (BOOL)performAction:(NSInteger)arg1 onElement:(id)arg2 value:(id)arg3 error:(id *)arg4;
- (void)performWhenMenuOpens:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)registerForAXNotificationsForApplicationWithPID:(NSInteger)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeObserver:(id)arg1 forAXNotification:(id)arg2;
- (BOOL)setAttribute:(id)arg1 value:(id)arg2 element:(id)arg3 outError:(id *)arg4;
- (id)snapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 error:(id *)arg4;
- (id)systemApplication;


@end

