// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCUIAccessibilityInterface-Protocol.h"

@class NSMutableDictionary, NSString;


@protocol XCUIApplicationProcessTracker;
@protocol XCUIRemoteAXInterface;

@interface XCAXClient_iOS : NSObject <XCUIAccessibilityInterface>
{
    id <XCUIApplicationProcessTracker> _applicationProcessTracker;
    id <XCUIRemoteAXInterface> _remoteAXInterface;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_userTestingNotificationHandlers;
    NSMutableDictionary *_cachedAccessibilityLoadedValuesForPIDs;
    NSUInteger _alertNotificationCounter;
}

@property double AXTimeout;
@property NSUInteger alertNotificationCounter;
@property(readonly) id <XCUIApplicationProcessTracker> applicationProcessTracker;
@property(retain) NSMutableDictionary *cachedAccessibilityLoadedValuesForPIDs;
@property(retain) NSObject<OS_dispatch_queue> *queue;
@property(readonly) id <XCUIRemoteAXInterface> remoteAXInterface;
@property(retain) NSMutableDictionary *userTestingNotificationHandlers;

+ (id)sharedClient;
- (BOOL)_loadAccessibility:(id *)arg1;
- (BOOL)_registerForAXNotification:(NSInteger)arg1 error:(id *)arg2;
- (BOOL)_setAXTimeout:(double)arg1 error:(id *)arg2;
- (id)activeApplications;
- (id)addObserverForAXNotification:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (id)attributesForElement:(id)arg1 attributes:(id)arg2;
- (id)attributesForElement:(id)arg1 attributes:(id)arg2 error:(id *)arg3;
- (id)attributesForElementSnapshot:(id)arg1 attributeList:(id)arg2;
- (BOOL)cachedAccessibilityLoadedValueForPID:(NSInteger)arg1;
- (id)defaultParameters;
- (BOOL)enableFauxCollectionViewCells:(id *)arg1;
- (void)handleAccessibilityNotification:(NSInteger)arg1 withPayload:(id)arg2;
- (void)handleUserTestingNotification:(id)arg1;
- (id)hitTestElement:(id)arg1 withPoint:(CGPoint)arg2 error:(id *)arg3;
- (id)initWithApplicationProcessTracker:(id)arg1 remoteAXInterface:(id)arg2;
- (id)interruptingUIElementsAffectingSnapshot:(id)arg1;
- (BOOL)loadAccessibility:(id *)arg1;
- (id)localizableStringsDataForActiveApplications;
- (void)notifyOnNextOccurrenceOfUserTestingEvent:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)notifyWhenEventLoopIsIdleForApplication:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)notifyWhenNoAnimationsAreActiveForApplication:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)notifyWhenViewControllerViewDidAppearReply:(CDUnknownBlockType)arg1;
- (void)notifyWhenViewControllerViewDidDisappearReply:(CDUnknownBlockType)arg1;
- (id)parameterizedAttribute:(id)arg1 forElement:(id)arg2 parameter:(id)arg3;
- (BOOL)performAction:(NSInteger)arg1 onElement:(id)arg2 value:(id)arg3 error:(id *)arg4;
- (void)registerForAXNotificationsForApplicationWithPID:(NSInteger)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeObserver:(id)arg1 forAXNotification:(id)arg2;
- (BOOL)setAttribute:(id)arg1 value:(id)arg2 element:(id)arg3 outError:(id *)arg4;
- (id)snapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 error:(id *)arg4;
- (id)systemApplication;


@end

