// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//



#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSSet, NSString;

@interface XCKeyMappingPath : NSObject <NSCopying>
{
    NSUInteger _keyState;
    XCKeyMappingPath *_next;
    NSSet *_inputs;
    NSString *_output;
    NSUInteger _length;
    NSString *_producedString;
}

@property(readonly, copy) NSSet *inputs;
@property(readonly, getter=isComplete) BOOL complete;
@property(readonly, getter=isEmpty) BOOL empty;
@property(readonly) NSUInteger keyState;
@property(readonly) NSUInteger length;
@property(readonly, copy) XCKeyMappingPath *next;
@property(readonly, copy) NSString *output;
@property(readonly, copy) NSString *producedString;

+ (id)emptyPath;
+ (id)pathWithKeyState:(NSUInteger)arg1 next:(id)arg2 inputs:(id)arg3 output:(id)arg4;
- (id)initWithKeyState:(NSUInteger)arg1 next:(id)arg2 inputs:(id)arg3 output:(id)arg4;
- (id)inputSequenceWithRequiredFlags:(NSUInteger)arg1 excludedFlags:(NSUInteger)arg2;
- (id)inputWithRequiredFlags:(NSUInteger)arg1 excludedFlags:(NSUInteger)arg2;

@end

