// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSArray, NSMutableArray;

@interface XCPointerEventPath : NSObject <NSSecureCoding>
{
    NSMutableArray *_pointerEvents;
    BOOL _immutable;
    NSUInteger _pathType;
    NSUInteger _index;
    NSUInteger _deviceID;
    CGPoint _initialMouseLocation;
}

@property NSUInteger deviceID;
@property BOOL immutable;
@property NSUInteger index;
@property(readonly) CGPoint initialMouseLocation;
@property(readonly) NSUInteger pathType;
@property(readonly) NSArray *pointerEvents;

- (void)_addPointerEvent:(id)arg1;
- (void)dragWithButton:(NSUInteger)arg1 toPoint:(CGPoint)arg2 atOffset:(double)arg3 duration:(double)arg4;
- (id)firstEventAfterOffset:(double)arg1;
- (id)initForMouseEvents;
- (id)initForMouseEventsAtLocation:(CGPoint)arg1;
- (id)initForMouseEventsWithDeviceID:(NSUInteger)arg1 atLocation:(CGPoint)arg2;
- (id)initForTextInput;
- (id)initForTouchAtPoint:(CGPoint)arg1 offset:(double)arg2;
- (id)initForTouchBarAtPoint:(CGPoint)arg1 offset:(double)arg2;
- (id)lastEventBeforeOffset:(double)arg1;
- (void)liftUpAtOffset:(double)arg1;
- (void)moveMouseToPoint:(CGPoint)arg1 atOffset:(double)arg2 duration:(double)arg3;
- (void)moveToPoint:(CGPoint)arg1 atOffset:(double)arg2;
- (void)pressButton:(NSUInteger)arg1 atOffset:(double)arg2 clickCount:(NSUInteger)arg3;
- (void)pressDownAtOffset:(double)arg1;
- (void)pressDownWithPressure:(double)arg1 atOffset:(double)arg2;
- (void)pressDownWithPressure:(double)arg1 stage:(NSUInteger)arg2 phase:(NSUInteger)arg3 atOffset:(double)arg4;
- (void)releaseButton:(NSUInteger)arg1 atOffset:(double)arg2 clickCount:(NSUInteger)arg3;
- (void)scrollAtPoint:(CGPoint)arg1 byLines:(NSInteger)arg2 atOffset:(double)arg3;
- (void)scrollWithDeltaVector:(CGVector)arg1 atOffset:(double)arg2 duration:(double)arg3;
- (void)setModifiers:(NSUInteger)arg1 mergeWithCurrentModifierFlags:(BOOL)arg2 atOffset:(double)arg3;
- (void)typeKey:(id)arg1 modifiers:(NSUInteger)arg2 atOffset:(double)arg3;
- (void)typeText:(id)arg1 atOffset:(double)arg2 typingSpeed:(NSUInteger)arg3 shouldRedact:(BOOL)arg4;

@end

