// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSArray, NSDictionary, NSMutableDictionary, NSString;

@interface XCTAggregateSuiteRunStatistics : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_lastTestIdentifier;
    NSMutableDictionary *_recordMap;
}

@property(readonly) NSDictionary *dictionaryRepresentation;
@property(copy) NSString *lastTestIdentifier;
@property(readonly) NSMutableDictionary *recordMap;
@property(readonly) NSUInteger suiteRecordCount;
@property(readonly) NSArray *suiteRecords;

- (void)addSuiteRecord:(id)arg1;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (BOOL)isEqualToStatistics:(id)arg1;
- (id)recordForSuiteNamed:(id)arg1;

@end

