// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray, NSMutableDictionary;

@interface XCTActivityRecordStack : NSObject
{
    NSMutableArray *_storage;
    NSMutableDictionary *_aggregationRecords;
}

@property(readonly) NSDictionary *aggregationRecords;

- (NSInteger)depth;
- (void)didFinishActivity:(id)arg1 testCase:(id)arg2 observationCenter:(id)arg3;
- (id)topActivity;
- (void)unwindRemainingActivitiesWithTestCase:(id)arg1 observationCenter:(id)arg2;
- (id)willStartActivityWithTitle:(id)arg1 type:(id)arg2 testCase:(id)arg3 observationCenter:(id)arg4;

@end

