// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2018 09:07:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>



@interface XCTAggregateSuiteRunStatisticsRecord : NSObject <NSSecureCoding>
{
    NSString *_suiteName;
    NSUInteger _executionCount;
    NSUInteger _failureCount;
    NSUInteger _unexpectedExceptionCount;
}

@property(readonly) NSUInteger executionCount;
@property(readonly) NSUInteger failureCount;
@property(readonly) NSString *suiteName;
@property(readonly) NSUInteger unexpectedExceptionCount;

- (id)initWithSuiteName:(id)arg1 executionCount:(NSUInteger)arg2 failureCount:(NSUInteger)arg3 unexpectedExceptionCount:(NSUInteger)arg4;
- (BOOL)isEqualToStatisticsRecord:(id)arg1;

@end

