// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2018 09:07:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSDictionary, _XCTContextImplementation;

@interface XCTContext : NSObject
{
    id _internalImplementation;
}

@property(readonly) NSDictionary *aggregationRecords;
@property(retain) _XCTContextImplementation *internalImplementation;

+ (id)_currentContextInThread:(id)arg1;
+ (void)_runActivityNamed:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (BOOL)_shouldReportActivityWithType:(id)arg1;
+ (id)currentContext;
+ (id)currentContextInThread:(id)arg1;
+ (BOOL)hasContextInThread:(id)arg1;
+ (void)popCurrentContextInThread:(id)arg1;
+ (void)pushCurrentContext:(id)arg1 inThread:(id)arg2;
+ (void)runActivityNamed:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)runInContextForTestCase:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (BOOL)shouldReportActivityWithType:(id)arg1 inTestMode:(NSInteger)arg2;
- (void)_runActivityNamed:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)_runActivityNamed:(id)arg1 type:(id)arg2 block:(CDUnknownBlockType)arg3;
- (NSInteger)activityRecordStackDepth;
- (void)didFinishActivity:(id)arg1;
- (id)initInternally;
- (id)topActivity;
- (void)unwindRemainingActivities;
- (id)willStartActivityWithTitle:(id)arg1 type:(id)arg2;

@end

