// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCDebugLogDelegate-Protocol.h"
#import "XCTASDebugLogDelegate-Protocol.h"
#import "XCTRunnerIDESessionDelegate-Protocol.h"

@class NSMutableArray, NSString, XCTestConfiguration;
@protocol OS_dispatch_queue;

@interface XCTestDriver : NSObject <XCTRunnerIDESessionDelegate, XCDebugLogDelegate, XCTASDebugLogDelegate>
{
    NSInteger _debugMessageBufferOverflow;
    XCTestConfiguration *_testConfiguration;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableArray *_debugMessageBuffer;
}

@property(retain) NSMutableArray *debugMessageBuffer;
@property NSInteger debugMessageBufferOverflow;
@property(readonly) NSObject<OS_dispatch_queue> *queue;
@property(readonly) XCTestConfiguration *testConfiguration;

+ (id)sharedTestDriver;
- (void)IDESessionDidDisconnect:(id)arg1;
- (void)_queue_flushDebugMessageBufferWithBlock:(CDUnknownBlockType)arg1;
- (BOOL)_readyIDESession:(id)arg1 forTestRunSession:(id)arg2 error:(id *)arg3;
- (id)initWithTestConfiguration:(id)arg1;
- (void)logDebugMessage:(id)arg1;
- (void)logStartupInfo;
- (void)printBufferedDebugMessages;
- (void)reportStallOnMainThreadInTestCase:(id)arg1 method:(id)arg2 file:(id)arg3 line:(NSUInteger)arg4;
- (void)runTestConfiguration:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)runTestSuite:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (BOOL)runTestsAndReturnError:(id *)arg1;


@end

