// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, XCTestRun;

@interface XCTest : NSObject
{
    id _internal;
}

@property(readonly) NSString *_classNameForReporting;
@property(readonly) NSString *_methodNameForReporting;
@property(readonly) Class _requiredTestRunBaseClass;
@property(readonly) NSString *languageAgnosticTestClassName;
@property(readonly) NSString *languageAgnosticTestMethodName;
@property(readonly, copy) NSString *name;
@property(readonly) NSString *nameForLegacyLogging;
@property(readonly) NSUInteger testCaseCount;
@property(readonly) XCTestRun *testRun;
@property(readonly) Class testRunClass;

+ (id)languageAgnosticTestClassNameForTestClass:(Class)arg1;
- (NSInteger)defaultExecutionOrderCompare:(id)arg1;
- (void)performTest:(id)arg1;
- (void)removeTestsWithNames:(id)arg1;
- (void)runTest;
- (void)setUp;
- (void)tearDown;

@end

