// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSArray, NSDictionary, NSNumber, NSSet, NSString, NSURL, NSUUID, XCTAggregateSuiteRunStatistics;

@interface XCTestConfiguration : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _reportResultsToIDE;
    BOOL _testsDrivenByIDE;
    BOOL _disablePerformanceMetrics;
    BOOL _treatMissingBaselinesAsFailures;
    BOOL _reportActivities;
    BOOL _testsMustRunOnMainThread;
    BOOL _initializeForUITesting;
    BOOL _gatherLocalizableStringsData;
    BOOL _emitOSLogs;
    NSString *_absolutePath;
    NSString *_testBundleRelativePath;
    NSURL *_testBundleURL;
    NSSet *_testsToRun;
    NSSet *_testsToSkip;
    NSUUID *_sessionIdentifier;
    NSURL *_baselineFileURL;
    NSString *_baselineFileRelativePath;
    NSString *_targetApplicationPath;
    NSString *_targetApplicationBundleID;
    NSDictionary *_testApplicationDependencies;
    NSDictionary *_testApplicationUserOverrides;
    NSString *_productModuleName;
    NSDictionary *_targetApplicationEnvironment;
    NSArray *_targetApplicationArguments;
    XCTAggregateSuiteRunStatistics *_aggregateStatisticsBeforeCrash;
    NSString *_automationFrameworkPath;
    NSString *_bridgedProcessAutomationFrameworkPath;
    NSInteger _systemAttachmentLifetime;
    NSInteger _userAttachmentLifetime;
    NSInteger _testExecutionOrdering;
    NSNumber *_randomExecutionOrderingSeed;
}

@property(copy) NSString *absolutePath;
@property(copy) XCTAggregateSuiteRunStatistics *aggregateStatisticsBeforeCrash;
@property(copy) NSString *automationFrameworkPath;
@property(copy) NSString *baselineFileRelativePath;
@property(copy, nonatomic) NSURL *baselineFileURL;
@property(copy) NSString *bridgedProcessAutomationFrameworkPath;
@property BOOL disablePerformanceMetrics;
@property BOOL emitOSLogs;
@property BOOL gatherLocalizableStringsData;
@property BOOL initializeForUITesting;
@property(copy) NSString *productModuleName;
@property(retain) NSNumber *randomExecutionOrderingSeed;
@property BOOL reportActivities;
@property BOOL reportResultsToIDE;
@property(copy) NSUUID *sessionIdentifier;
@property NSInteger systemAttachmentLifetime;
@property(copy) NSArray *targetApplicationArguments;
@property(copy) NSString *targetApplicationBundleID;
@property(copy) NSDictionary *targetApplicationEnvironment;
@property(copy) NSString *targetApplicationPath;
@property(copy) NSDictionary *testApplicationDependencies;
@property(copy) NSDictionary *testApplicationUserOverrides;
@property(copy) NSString *testBundleRelativePath;
@property(copy, nonatomic) NSURL *testBundleURL;
@property NSInteger testExecutionOrdering;
@property BOOL testsDrivenByIDE;
@property BOOL testsMustRunOnMainThread;
@property(copy) NSSet *testsToRun;
@property(copy) NSSet *testsToSkip;
@property BOOL treatMissingBaselinesAsFailures;
@property NSInteger userAttachmentLifetime;
@property(readonly) NSInteger testMode;

+ (id)activeTestConfiguration;
+ (id)configurationWithContentsOfFile:(id)arg1;
+ (void)setActiveTestConfiguration:(id)arg1;
- (BOOL)writeToFile:(id)arg1;

@end

