// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  6 2021 20:43:33).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTImageEncoding.h"

@interface XCTImageEncoding (XCTImageQuality)
+ (double)compressionQualityForQuality:(NSInteger)arg1;
+ (BOOL)isValidCompressionQuality:(double)arg1 andCompressionQualityObject:(id)arg2;
+ (double)systemScreenshotCompressionQuality;
+ (id)systemScreenshotEncoding;
+ (id)systemScreenshotUniformTypeIdentifier;
+ (id)uniformTypeIdentifierForQuality:(NSInteger)arg1;
- (id)initWithImageQuality:(NSInteger)arg1;
@end

