// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>
#import <stdatomic.h>

#import "XCTSymbolInfoProviding-Protocol.h"

@class NSSet, NSString;

@interface XCTInProcessSymbolicationService : NSObject <XCTSymbolInfoProviding>
{
    struct atomic_flag _symbolicatorInitialized;
    NSSet *_imageNames;
    CDStruct_7da0dd4a _symbolicationFunctions;
}

@property(readonly, copy) NSSet *imageNames;
@property(readonly) CDStruct_7da0dd4a symbolicationFunctions;
@property(readonly) struct _CSTypeRef symbolicator;
@property(readonly) struct atomic_flag symbolicatorInitialized;

+ (id)imageNamesFromEnvironmentVariables:(id)arg1;
+ (void)registerSharedServiceWithConfiguration:(id)arg1;
+ (CDStruct_7da0dd4a)standardSymbolicationFunctions;
- (void)_prepareForSymbolication;
- (id)initWithImageNames:(id)arg1;
- (id)initWithImageNames:(id)arg1 symbolicationFunctions:(CDStruct_7da0dd4a)arg2;
- (id)symbolInfoForAddressInCurrentProcess:(NSUInteger)arg1 error:(id *)arg2;


@end

