// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSDictionary;

@interface XCTMeasureOptions : NSObject
{
    BOOL _enableParallelizedSampling;
    BOOL _scheduleKickOffOnNewThread;
    BOOL _allowContinuousSampling;
    BOOL _discardTraceIteration;
    BOOL _discardFirstIteration;
    BOOL _traceCollectionEnabled;
    NSUInteger _invocationOptions;
    NSUInteger _iterationCount;
    NSDictionary *_performanceTestConfiguration;
    double _quiesceCpuIdlePercent;
    double _quiesceCpuIdleTimeLimit;
}

@property(nonatomic) BOOL allowConcurrentIterations;
@property(nonatomic) BOOL allowContinuousSampling;
@property(nonatomic) BOOL discardFirstIteration;
@property(nonatomic) BOOL discardTraceIteration;
@property(readonly, nonatomic) NSUInteger instrumentAutomatic;
@property(readonly, nonatomic) NSDictionary *instrumentOptions;
@property(nonatomic) NSUInteger invocationOptions;
@property(nonatomic) NSUInteger iterationCount;
@property(retain, nonatomic) NSDictionary *performanceTestConfiguration;
@property(nonatomic) double quiesceCpuIdlePercent;
@property(nonatomic) double quiesceCpuIdleTimeLimit;
@property(nonatomic) BOOL traceCollectionEnabled;

+ (id)defaultOptions;
- (void)applyPerformanceTestConfiguration;
- (id)initWithInstrumentOptionsDictionary:(id)arg1;

@end

