// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface XCTMetric : NSObject
{
    NSString *_identifier;
    NSString *_name;
    NSString *_units;
    NSDictionary *_baseline;
    NSDictionary *_defaultBaseline;
    NSArray *_measurements;
}

@property(copy) NSDictionary *baseline;
@property(copy) NSDictionary *defaultBaseline;
@property(copy) NSString *identifier;
@property(copy) NSArray *measurements;
@property(copy) NSString *name;
@property(copy) NSString *units;


@end

