// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  6 2021 20:43:33).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface XCTMeasurement : NSObject
{
    NSString *_identifier;
    NSString *_units;
    NSString *_name;
    NSDictionary *_baseline;
    NSDictionary *_defaultBaseline;
    NSArray *_measurements;
    NSInteger _polarity;
}

@property(copy) NSDictionary *baseline;
@property(copy) NSDictionary *defaultBaseline;
@property(copy) NSString *identifier;
@property(copy) NSArray *measurements;
@property(copy) NSString *name;
@property NSInteger polarity;
@property(copy) NSString *units;


@end

