// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTestExpectation.h"

@class NSNotificationCenter, NSString, _XCTNSNotificationExpectationImplementation;

@interface XCTNSNotificationExpectation : XCTestExpectation
{
    _XCTNSNotificationExpectationImplementation *_internal;
}

@property(copy) CDUnknownBlockType handler;
@property(retain) _XCTNSNotificationExpectationImplementation *internal;
@property(readonly) NSNotificationCenter *notificationCenter;
@property(readonly, copy) NSString *notificationName;
@property(readonly) id observedObject;

- (void)cleanup;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 object:(id)arg2;
- (id)initWithName:(id)arg1 object:(id)arg2 notificationCenter:(id)arg3;

@end

