// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTestManager_TestsInterface-Protocol.h"
#import "XCUIRemoteAXInterface-Protocol.h"

@class NSMutableDictionary, NSString, NSXPCConnection;
@protocol OS_dispatch_queue, XCTUIApplicationMonitor, XCTestManager_ManagerInterface, XCUIAXNotificationHandling;


@protocol XCTUIApplicationMonitor;
@protocol XCUIAXNotificationHandling;
@protocol XCTestManager_ManagerInterface;

@interface XCTRunnerDaemonSession : NSObject <XCTestManager_TestsInterface, XCUIRemoteAXInterface>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <XCTUIApplicationMonitor> _applicationMonitor;
    id <XCUIAXNotificationHandling> _accessibilityClient;
    NSXPCConnection *_connection;
    NSUInteger _daemonProtocolVersion;
    NSMutableDictionary *_invalidationHandlers;
}

@property id <XCUIAXNotificationHandling> accessibilityClient;
@property id <XCTUIApplicationMonitor> applicationMonitor;
@property(readonly) BOOL axNotificationsIncludeElement;
@property(readonly) NSXPCConnection *connection;
@property NSUInteger daemonProtocolVersion;
@property(readonly) id <XCTestManager_ManagerInterface> daemonProxy;
@property(retain) NSMutableDictionary *invalidationHandlers;
@property(retain) NSObject<OS_dispatch_queue> *queue;
@property(readonly) BOOL useLegacyEventCoordinateTransformationPath;
@property(readonly) BOOL useLegacyScreenshotPath;
@property(readonly) BOOL useLegacySnapshotPath;
@property(readonly) BOOL usePointTransformationsForFrameConversions;

+ (id)sharedSession;
- (void)_XCT_applicationWithBundleID:(id)arg1 didUpdatePID:(NSInteger)arg2 andState:(NSUInteger)arg3;
- (void)_XCT_receivedAccessibilityNotification:(NSInteger)arg1 fromElement:(id)arg2 payload:(id)arg3;
- (void)_XCT_receivedAccessibilityNotification:(NSInteger)arg1 withPayload:(id)arg2;
- (void)_reportInvalidation;
- (void)enableFauxCollectionViewCells:(CDUnknownBlockType)arg1;
- (void)fetchAttributes:(id)arg1 forElement:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)fetchAttributesForElement:(id)arg1 attributes:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)fetchParameterizedAttribute:(id)arg1 forElement:(id)arg2 parameter:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)getDeviceOrientationWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithConnection:(id)arg1;
- (void)injectAssistantRecognitionStrings:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)injectVoiceRecognitionAudioInputPaths:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)launchApplicationWithBundleID:(id)arg1 arguments:(id)arg2 environment:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)loadAccessibilityWithTimeout:(double)arg1 reply:(CDUnknownBlockType)arg2;
- (void)performAccessibilityAction:(NSInteger)arg1 onElement:(id)arg2 value:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)performDeviceEvent:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)registerForAccessibilityNotification:(NSInteger)arg1 reply:(CDUnknownBlockType)arg2;
- (id)registerInvalidationHandler:(CDUnknownBlockType)arg1;
- (void)requestAutomationSessionForTestTargetWithPID:(NSInteger)arg1 preferredBackendPath:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)requestBackgroundAssertionForPID:(NSInteger)arg1 reply:(CDUnknownBlockType)arg2;
- (void)requestBundleIDForPID:(NSInteger)arg1 reply:(CDUnknownBlockType)arg2;
- (void)requestDTServiceHubConnectionWithReply:(CDUnknownBlockType)arg1;
- (void)requestElementAtPoint:(CGPoint)arg1 reply:(CDUnknownBlockType)arg2;
- (void)requestIDEConnectionTransportForSessionIdentifier:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)requestScreenshotOfScreenWithID:(NSUInteger)arg1 withRect:(CGRect)arg2 formatUTI:(id)arg3 compressionQuality:(double)arg4 imageFormatRespected:(BOOL *)arg5 withReply:(CDUnknownBlockType)arg6;
- (void)requestScreenshotWithReply:(CDUnknownBlockType)arg1;
- (void)requestSiriEnabledStatus:(CDUnknownBlockType)arg1;
- (void)requestSnapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)requestSpindumpWithSpecification:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)sendString:(id)arg1 maximumFrequency:(NSUInteger)arg2 completion:(CDUnknownBlockType)arg3;
- (void)setAXTimeout:(double)arg1 reply:(CDUnknownBlockType)arg2;
- (void)setAttribute:(id)arg1 value:(id)arg2 element:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)setLocalizableStringsDataGatheringEnabled:(BOOL)arg1 reply:(CDUnknownBlockType)arg2;
- (void)snapshotForElement:(id)arg1 attributes:(id)arg2 parameters:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)startMonitoringApplicationWithBundleID:(id)arg1;
- (void)startSiriUIRequestWithAudioFileURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)startSiriUIRequestWithText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)synthesizeEvent:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)terminateApplicationWithBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)unregisterForAccessibilityNotification:(NSInteger)arg1 registrationToken:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (void)unregisterInvalidationHandlerWithToken:(id)arg1;
- (void)updateDeviceOrientation:(NSInteger)arg1 completion:(CDUnknownBlockType)arg2;


@end

