// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  9 2018 18:32:08).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTRunnerAutomationSession-Protocol.h"

@class NSString, NSXPCConnection;
@protocol XCUICapabilities;

@interface XCTRunnerAutomationSession : NSObject <XCTRunnerAutomationSession>
{
    NSInteger _connectionPid;
    NSXPCConnection *_connection;
    id <XCUICapabilities> _capabilities;
}

@property(readonly) id <XCUICapabilities> capabilities;
@property(readonly) NSXPCConnection *connection;
@property(readonly) NSInteger connectionPid;
@property(readonly) BOOL supportsAnimationsIdleNotifications;
@property(readonly) BOOL supportsMainRunLoopIdleNotifications;

- (id)initWithEndpoint:(id)arg1 pid:(NSInteger)arg2 capabilities:(id)arg3;
- (id)matchesForQuery:(id)arg1 error:(id *)arg2;
- (void)notifyWhenAnimationsAreIdle:(CDUnknownBlockType)arg1;
- (void)notifyWhenMainRunLoopIsIdle:(CDUnknownBlockType)arg1;


@end

