// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  6 2021 20:43:33).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@interface XCTRerunPolicy : NSObject <NSSecureCoding>
{
    NSInteger _rerunMode;
    NSInteger _maximumIterations;
}

@property(readonly) NSInteger maximumIterations;
@property(readonly) NSInteger rerunMode;

+ (id)defaultRerunPolicy;
+ (NSInteger)rerunModeFromString:(id)arg1;
+ (id)stringFromRerunMode:(NSInteger)arg1;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFixedIterations:(NSInteger)arg1;
- (id)initWithMaximumIterationsUntilFailure:(NSInteger)arg1;
- (id)initWithMaximumIterationsUntilSuccess:(NSInteger)arg1;
- (id)initWithRerunMode:(NSInteger)arg1 maximumIterations:(NSInteger)arg2;
- (BOOL)isDefaultPolicy;

@end

