// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSString, XCTSourceCodeLocation;

@interface XCTSourceCodeSymbolInfo : NSObject <NSSecureCoding>
{
    NSString *_imageName;
    NSString *_symbolName;
    XCTSourceCodeLocation *_location;
}

@property(readonly, copy) NSString *imageName;
@property(readonly) XCTSourceCodeLocation *location;
@property(readonly, copy) NSString *symbolName;

- (id)initWithImageName:(id)arg1 symbolName:(id)arg2 location:(id)arg3;

@end

