// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@interface XCTSkippedTestContext : NSObject
{
    NSString *_summary;
    NSString *_explanation;
    NSString *_evaluatedExpression;
    NSString *_message;
    NSString *_filePath;
    NSUInteger _lineNumber;
}

@property(readonly, copy) NSString *evaluatedExpression;
@property(readonly, copy) NSString *explanation;
@property(readonly, copy) NSString *filePath;
@property(readonly) NSUInteger lineNumber;
@property(readonly, copy) NSString *message;
@property(readonly, copy) NSString *summary;

- (id)initWithError:(id)arg1 evaluatedExpression:(id)arg2 message:(id)arg3 filePath:(id)arg4 lineNumber:(NSUInteger)arg5;
- (id)initWithException:(id)arg1 evaluatedExpression:(id)arg2 message:(id)arg3 filePath:(id)arg4 lineNumber:(NSUInteger)arg5;
- (id)initWithExpectedValue:(BOOL)arg1 evaluatedExpression:(id)arg2 message:(id)arg3 filePath:(id)arg4 lineNumber:(NSUInteger)arg5;
- (id)initWithExplanation:(id)arg1 evaluatedExpression:(id)arg2 message:(id)arg3 filePath:(id)arg4 lineNumber:(NSUInteger)arg5;

@end

