// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  6 2021 20:43:33).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSDictionary, XCTTestIdentifier;

@interface XCTTestIdentifierSet : NSObject <NSCopying, NSFastEnumeration, NSSecureCoding>
{
}

@property(readonly) XCTTestIdentifier *anyTestIdentifier;
@property(readonly) NSUInteger count;
@property(readonly) NSDictionary *testIdentifiersGroupedByFirstComponentIdentifier;

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)emptyTestIdentifierSet;
- (id)builder;
- (Class)classForCoder;
- (BOOL)containsTestIdentifier:(id)arg1;
- (NSUInteger)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(NSUInteger)arg3;
- (void)enumerateTestIdentifiersUsingBlock:(CDUnknownBlockType)arg1;
- (id)initWithArray:(id)arg1;
- (id)initWithSet:(id)arg1;
- (id)initWithTestIdentifier:(id)arg1;
- (id)initWithTestIdentifiers:(const id *)arg1 count:(NSUInteger)arg2;
- (id)setByAddingTestIdentifiersFromSet:(id)arg1;
- (id)setByApplyingBlock:(CDUnknownBlockType)arg1;

@end

