// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@interface XCTUniformTypeIdentifier : NSObject
{
}

+ (id)GIF;
+ (id)JPEG;
+ (id)PNG;
+ (id)TIFF;
+ (id)XMLPropertyList;
+ (id)data;
+ (id)inferredUTIForFileExtension:(id)arg1;
+ (BOOL)isImageUTI:(id)arg1;
+ (id)plainText;
+ (id)zipArchive;

@end

