// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul 30 2018 09:07:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCUIApplicationProcessTracker-Protocol.h"

@class NSNumber, NSString, XCTApplicationStateSnapshot, XCUIApplication, XCUIApplicationImpl, XCUIApplicationProcess, XCUIApplicationRegistry;

@protocol XCUIApplicationMonitor <NSObject, XCUIApplicationProcessTracker>
- (void)acquireBackgroundAssertionForPID:(NSInteger)arg1 reply:(void (^)(BOOL))arg2;
- (XCUIApplicationImpl *)applicationImplementationForApplicationAtPath:(NSString *)arg1 bundleID:(NSString *)arg2;
- (void)applicationWithBundleID:(NSString *)arg1 didUpdatePID:(NSInteger)arg2 state:(NSUInteger)arg3;
- (void)crashInProcessWithBundleID:(NSString *)arg1 path:(NSString *)arg2 pid:(NSInteger)arg3 symbol:(NSString *)arg4;
- (void)launchRequestedForApplicationProcess:(XCUIApplicationProcess *)arg1;
- (XCUIApplication *)monitoredApplicationWithProcessIdentifier:(NSInteger)arg1;
- (void)processWithToken:(NSNumber *)arg1 exitedWithStatus:(NSInteger)arg2;
- (void)requestAutomationSessionForTestTargetWithPID:(NSInteger)arg1 preferredBackendPath:(NSString *)arg2 reply:(void (^)(id <XCTRunnerAutomationSession>, NSError *))arg3;
- (void)stopTrackingProcessWithToken:(NSNumber *)arg1;
- (void)terminateApplicationProcess:(XCUIApplicationProcess *)arg1 withToken:(id)arg2;
- (void)terminationTrackedForApplicationProcess:(XCUIApplicationProcess *)arg1;
- (void)updatedApplicationStateSnapshot:(XCTApplicationStateSnapshot *)arg1;
- (void)waitForUnrequestedTerminationOfLaunchedApplicationsWithTimeout:(double)arg1;
@end

