// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import <UIKit/UIDevice.h>

@class NSString, XCUIRemote, XCUISiriService;
@protocol XCUIAccessibilityInterface, XCUIApplicationAutomationSessionProviding, XCUIApplicationManaging, XCUIApplicationMonitor, XCUIDeviceDiagnostics, XCUIDeviceEventAndStateInterface, XCUIEventSynthesizing, XCUIInterruptionMonitoring, XCUIResetAuthorizationStatusOfProtectedResourcesInterface, XCUIScreenDataSource, XCUIXcodeApplicationManaging;


@protocol XCUIAccessibilityInterface;
@protocol XCUIXcodeApplicationManaging;

@interface XCUIDevice : NSObject
{
    BOOL _isLocal;
    BOOL _isSimulatorDevice;
    NSInteger _platform;
    id <XCUIAccessibilityInterface> _accessibilityInterface;
    id <XCUIApplicationMonitor> _applicationMonitor;
    id <XCUIEventSynthesizing> _eventSynthesizer;
    id <XCUIApplicationManaging> _platformApplicationManager;
    id <XCUIXcodeApplicationManaging> _xcodeApplicationManager;
    id <XCUIDeviceEventAndStateInterface> _deviceEventAndStateInterface;
    id <XCUIApplicationAutomationSessionProviding> _applicationAutomationSessionProvider;
    XCUISiriService *_siriService;
    id <XCUIScreenDataSource> _screenDataSource;
    NSString *_uniqueIdentifier;
    XCUIRemote *_remote;
    id <XCUIInterruptionMonitoring> _interruptionMonitor;
    id <XCUIResetAuthorizationStatusOfProtectedResourcesInterface> _resetAuthorizationStatusInterface;
    id <XCUIDeviceDiagnostics> _diagnosticsProvider;
}

@property(nonatomic) UIDeviceOrientation orientation;
@property(readonly) XCUISiriService *siriService;

+ (id)localDevice;
+ (void)setLocalDevice:(id)arg1;
+ (XCUIDevice *)sharedDevice;
- (void)_setOrientation:(NSInteger)arg1;
- (void)_silentPressButton:(NSInteger)arg1;
- (id)accessibilityInterface;
- (id)applicationAutomationSessionProvider;
- (id)applicationMonitor;
- (void)attachLocalizableStringsData;
- (BOOL)configuredForUITesting;
- (id)deviceEventAndStateInterface;
- (id)diagnosticAttachmentsForError:(id)arg1;
- (id)diagnosticsProvider;
- (id)eventSynthesizer;
- (void)holdHomeButtonForDuration:(double)arg1;
- (id)initLocalDeviceWithPlatform:(NSInteger)arg1;
- (id)initWithDiagnosticProvider:(id)arg1;
- (id)interruptionMonitor;
- (BOOL)isLocal;
- (BOOL)isSimulatorDevice;
- (id)mainScreen;
- (id)mainScreenOrError:(id *)arg1;
- (id)makeDiagnosticScreenshotAttachmentForDevice;
- (BOOL)performDeviceEvent:(id)arg1 error:(id *)arg2;
- (NSInteger)platform;
- (id)platformApplicationManager;
- (void)pressButton:(NSInteger)arg1;
- (void)pressLockButton;
- (id)remote;
- (void)remoteAutomationSessionDidDisconnect:(id)arg1;
- (id)resetAuthorizationStatusInterface;
- (void)rotateDigitalCrown:(double)arg1 velocity:(double)arg2;
- (id)screenDataSource;
- (id)screens;
- (id)screensOrError:(id *)arg1;
- (id)spindumpAttachmentForProcessID:(NSInteger)arg1 error:(id *)arg2;
- (BOOL)supportsPressureInteraction;
- (id)uniqueIdentifier;
- (id)xcodeApplicationManager;

@end

