// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, XCUIApplication;

@interface XCUISiriService : NSObject
{
    XCUIApplication *_siriApplication;
}

@property(readonly, getter=isEnabled) BOOL enabled;
@property(retain) XCUIApplication *siriApplication;

+ (id)siriService;
- (void)_assertSiriEnabled;
- (void)_waitForActivation;
- (void)activateWithVoiceRecognitionText:(id)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (void)injectAssistantRecognitionStrings:(id)arg1;
- (void)injectVoiceRecognitionAudioInputPaths:(id)arg1;

@end

