// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  6 2021 20:43:33).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class XCUIScreen;

@interface XCUIKnobControl : NSObject
{
    XCUIScreen *_screen;
}

@property(readonly) __weak XCUIScreen *screen;

- (id)initWithScreen:(id)arg1;
- (void)nudgeInDirection:(NSUInteger)arg1;
- (void)rotateByNumberOfClicks:(NSUInteger)arg1 clockwise:(BOOL)arg2;
- (void)select;

@end

