// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSMutableDictionary;

@interface XCUIApplicationImplDepot : NSObject
{
    NSMutableDictionary *_applicationImpls;
    id <XCUIDevice> _device;
}

@property(readonly) id <XCUIDevice> device;

- (id)_canonicalSpecifierFromSpecifier:(id)arg1;
- (id)_identifierFromSpecifier:(id)arg1;
- (id)applicationImplForSpecifier:(id)arg1;
- (id)initWithDevice:(id)arg1;

@end

