// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, NSURL;

@interface XCUIApplicationRegistryRecord : NSObject
{
    BOOL _isTestDependency;
    NSURL *_URL;
    NSString *_bundleIdentifier;
}

@property(readonly, copy) NSURL *URL;
@property(readonly, copy) NSString *bundleIdentifier;
@property(readonly) BOOL isTestDependency;

- (id)initWithURL:(id)arg1 bundleIdentifier:(id)arg2 isTestDependency:(BOOL)arg3;

@end

