// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSNumber, XCUIApplicationProcess;
@protocol XCUIElementSnapshotApplication;

@protocol XCUIApplicationProcessTracker <NSObject>
- (XCUIApplicationProcess *)applicationProcessWithPID:(NSInteger)arg1;
- (XCUIApplicationProcess *)applicationProcessWithToken:(NSNumber *)arg1;
- (id <XCUIElementSnapshotApplication>)monitoredApplicationWithProcessIdentifier:(NSInteger)arg1;
- (void)setApplicationProcess:(XCUIApplicationProcess *)arg1 forPID:(NSInteger)arg2;
- (void)setApplicationProcess:(XCUIApplicationProcess *)arg1 forToken:(NSNumber *)arg2;
@end

