// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr 12 2019 07:16:25).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class XCDeviceEvent;

@protocol XCUIDeviceEventAndStateInterface <NSObject>
- (void)getDeviceOrientationWithCompletion:(void (^)(NSInteger, NSError *))arg1;
- (void)performDeviceEvent:(XCDeviceEvent *)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)updateDeviceOrientation:(NSInteger)arg1 completion:(void (^)(BOOL, NSError *))arg2;
@end

