// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCActivityRecord.h"

@interface XCActivityRecord (UITesting)
+ (id)createSnapshotAsTextAttachment:(id)arg1 withBundleID:(id)arg2;
+ (id)createSnapshotAttachment:(id)arg1;
- (void)addLocalizableStringsData:(id)arg1;
- (void)addScreenImageData:(id)arg1 forceKeepAlways:(BOOL)arg2;
- (void)addSnapshot:(id)arg1;
- (void)addSnapshotAsText:(id)arg1 withBundleID:(id)arg2;
- (void)addSynthesizedEvent:(id)arg1;
- (void)attachDiagnosticScreenshotForDevice:(id)arg1;
- (void)attachDiagnosticScreenshotForScreen:(id)arg1;
@end

