// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet;

@interface XCSourceCodeRecording : NSObject
{
    NSUInteger _language;
    NSMutableArray *_treeNodes;
    NSMutableSet *_variableTreeNodes;
    NSArray *_reservedNames;
    NSMutableDictionary *_variableNameToContentNodeDictionary;
    NSInteger _nextVariableCount;
}

@property(retain, setter=_setTreeNodes:) NSArray *_treeNodes;
@property(readonly) NSUInteger language;
@property(retain) NSMutableDictionary *variableNameToContentNodeDictionary;

- (BOOL)_createAndShareLocalVariableUsingSourceNode:(id)arg1 atIndex:(NSInteger)arg2;
- (id)_nodes:(id)arg1 matchingDistanceFromRoot:(BOOL)arg2 variableContentNode:(id)arg3 withVariableName:(id)arg4 startingIndex:(NSInteger)arg5 replacedNodes:(NSInteger *)arg6 indexOfFirstReplacedNode:(NSInteger *)arg7;
- (void)_shareCommonSectionsInLocalVariables;
- (BOOL)_shareCommonSectionsUsingExistingLocalVariables;
- (BOOL)_shareLongestCommonSection_StartAtIndex:(NSInteger)arg1 nextCandidateIndex:(NSInteger *)arg2;
- (id)_sourceCodePrefixForVariableName:(id)arg1 variableType:(NSUInteger)arg2;
- (id)_stringRepresentationWithOptions:(NSUInteger)arg1 error:(id *)arg2;
- (id)_transformedVariablePrefixForLabel:(id)arg1;
- (id)_uniqueVariableNameWithName:(id)arg1;
- (NSUInteger)_variableClassTypeForVariableContentNode:(id)arg1;
- (id)_variableNameForElementType:(NSUInteger)arg1 label:(id)arg2 classType:(NSUInteger)arg3;
- (id)_variableNameForVariableContentNode:(id)arg1;
- (id)_variableSuffixForElementType:(NSUInteger)arg1 classType:(NSUInteger)arg2;
- (void)appendNode:(id)arg1 replaceLastNode:(BOOL)arg2;
- (id)copy;
- (id)initWithLanguage:(NSUInteger)arg1 reservedNames:(id)arg2;
- (id)stringRepresentationWithError:(id *)arg1;
- (id)variableNodeForNode:(id)arg1 withName:(id)arg2 variableType:(NSUInteger)arg3;

@end

