// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCUIElementEventTarget-Protocol.h"


@interface XCUIElementEmbeddedEventTarget <XCUIElementEventTarget>
{
}

- (BOOL)_swipe:(NSUInteger)arg1 withVelocity:(double)arg2 error:(id *)arg3;
- (BOOL)clickForDuration:(double)arg1 thenDragToElement:(id)arg2 withVelocity:(double)arg3 thenHoldForDuration:(double)arg4 error:(id *)arg5;
- (BOOL)clickWithError:(id *)arg1;
- (BOOL)doubleClickWithError:(id *)arg1;
- (BOOL)doubleTapWithError:(id *)arg1;
- (BOOL)hoverWithError:(id *)arg1;
- (BOOL)rightClickWithError:(id *)arg1;
- (BOOL)swipeDownWithError:(id *)arg1;
- (BOOL)swipeDownWithVelocity:(double)arg1 error:(id *)arg2;
- (BOOL)swipeLeftWithError:(id *)arg1;
- (BOOL)swipeLeftWithVelocity:(double)arg1 error:(id *)arg2;
- (BOOL)swipeRightWithError:(id *)arg1;
- (BOOL)swipeRightWithVelocity:(double)arg1 error:(id *)arg2;
- (BOOL)swipeUpWithError:(id *)arg1;
- (BOOL)swipeUpWithVelocity:(double)arg1 error:(id *)arg2;
- (BOOL)tapWithError:(id *)arg1;
- (BOOL)tapWithNumberOfTaps:(NSUInteger)arg1 numberOfTouches:(NSUInteger)arg2 error:(id *)arg3;
- (BOOL)twoFingerTapWithError:(id *)arg1;


@end

