// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSUUID, XCTScreenRecordingRequest, XCTScreenshotRequest;

@protocol XCUIScreenDataSource <NSObject>
- (void)requestBoundsForScreenWithIdentifier:(NSInteger)arg1 completion:(void (^)(CGRect, NSError *))arg2;
- (void)requestScaleForScreenWithIdentifier:(NSInteger)arg1 completion:(void (^)(double, NSError *))arg2;
- (void)requestScreenIdentifiersWithCompletion:(void (^)(NSArray *, NSError *))arg1;
- (void)requestScreenshotAttachmentWithRequest:(XCTScreenshotRequest *)arg1 withReply:(void (^)(XCTAttachmentFuture *, NSError *))arg2;
- (void)requestScreenshotWithRequest:(XCTScreenshotRequest *)arg1 withReply:(void (^)(XCTImage *, NSError *))arg2;
- (void)requestTraitsForScreenWithIdentifier:(NSInteger)arg1 completion:(void (^)(NSUInteger, NSError *))arg2;
- (void)startScreenRecordingWithRequest:(XCTScreenRecordingRequest *)arg1 withReply:(void (^)(XCTAttachmentFuture *, NSError *))arg2;
- (void)stopScreenRecordingWithUUID:(NSUUID *)arg1 withReply:(void (^)(NSError *))arg2;
@end

