// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol XCUIDevice;

@interface XCUIApplicationImplDepot : NSObject
{
    NSMutableDictionary *_applicationImpls;
    id <XCUIDevice> _device;
}

@property(readonly) id <XCUIDevice> device;

- (id)_canonicalSpecifierFromSpecifier:(id)arg1;
- (id)_identifierFromSpecifier:(id)arg1;
- (id)applicationImplForSpecifier:(id)arg1;
- (id)initWithDevice:(id)arg1;
- (void)resetDepotStateWithPlatformServicesProvider:(id)arg1;

@end

