// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


@protocol XCUIElementSnapshot;

@protocol XCUIElementSnapshotProviding <NSObject>
- (id <XCUIElementSnapshot>)snapshotWithError:(id *)arg1;
@end

