// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSString, XCAccessibilityElement, XCUIApplication, XCUIElement;

@interface XCUIAccessibilityAuditIssue : NSObject
{
    NSString *_compactDescription;
    NSString *_detailedDescription;
    NSUInteger _auditType;
    XCAccessibilityElement *_axElement;
    XCUIApplication *_application;
}

@property(readonly, nonatomic) XCUIApplication *application;
@property(readonly, nonatomic) NSUInteger auditType;
@property(readonly, nonatomic) XCAccessibilityElement *axElement;
@property(copy, nonatomic) NSString *compactDescription;
@property(copy, nonatomic) NSString *detailedDescription;
@property(readonly, nonatomic) XCUIElement *element;

- (NSUInteger)_xcuiAuditTypeForXCAXAuditType:(id)arg1;
- (id)initWithResult:(id)arg1 forApplication:(id)arg2;

@end

