// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCUIApplicationProcessManaging-Protocol.h"

@protocol XCUIPlatformApplicationServicesProviding;

__attribute__((visibility("hidden")))
@interface XCUIPlatformApplicationManager : NSObject <XCUIApplicationProcessManaging>
{
    id <XCUIPlatformApplicationServicesProviding> _platformApplicationServicesProvider;
}

@property(readonly) id <XCUIPlatformApplicationServicesProviding> platformApplicationServicesProvider;

+ (BOOL)_shouldRetryForLaunchError:(id)arg1;
- (id)initWithPlatformApplicationServicesProvider:(id)arg1;
- (void)launchProcessWithPath:(id)arg1 bundleID:(id)arg2 arguments:(id)arg3 environmentVariables:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)openDefaultApplicationForURL:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)openURL:(id)arg1 usingApplication:(id)arg2 completion:(CDUnknownBlockType)arg3;


@end

