// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSArray, NSDictionary, NSString, NSURL, XCUIApplicationSpecifier;
@protocol XCUIApplicationPlatformServicesProviderDelegate;

@protocol XCUIPlatformApplicationServicesProviding <NSObject>
- (void)beginMonitoringApplicationWithSpecifier:(XCUIApplicationSpecifier *)arg1;
- (void)launchApplicationWithPath:(NSString *)arg1 bundleID:(NSString *)arg2 arguments:(NSArray *)arg3 environment:(NSDictionary *)arg4 completion:(void (^)(BOOL, NSError *))arg5;
- (void)openDefaultApplicationForURL:(NSURL *)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)openURL:(NSURL *)arg1 usingApplication:(NSString *)arg2 completion:(void (^)(BOOL, NSError *))arg3;
- (void)requestApplicationSpecifierForPID:(NSInteger)arg1 reply:(void (^)(XCUIApplicationSpecifier *, NSError *))arg2;
- (void)terminateApplicationWithBundleID:(NSString *)arg1 pid:(NSInteger)arg2 completion:(void (^)(BOOL, NSError *))arg3;
@end

