// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSMutableString, XCAccessibilityElement;

@interface XCUIRecorderUtilities : NSObject
{
    NSUInteger _language;
    NSUInteger _platform;
    NSUInteger _compareSnapshotsLikePlatform;
    XCAccessibilityElement *_previousFocusedAccessibilityElement;
    NSMutableString *_previousTyping;
}

@property NSUInteger _compareSnapshotsLikePlatform;
@property NSUInteger language;
@property NSUInteger platform;
@property(retain) XCAccessibilityElement *previousFocusedAccessibilityElement;
@property(retain) NSMutableString *previousTyping;

+ (id)applicationNodeForLanguage:(NSUInteger)arg1;
+ (NSUInteger)currentPlatform;
- (id)_snapshotInTreeStartingWithSnapshot:(id)arg1 passingPredicateBlock:(CDUnknownBlockType)arg2;
- (id)_stringConstantForString:(id)arg1;
- (id)adjustedSnapshotForApplicationSnapshot:(id)arg1;
- (id)applicationNode;
- (id)assertHasFocusNode;
- (void)clearPreviousTyping;
- (id)commentNodeWithString:(id)arg1;
- (id)focusedAccessibilityElementForApplicationSnapshot:(id)arg1;
- (id)gestureNodesForKeyDownEventWithCharacters:(id)arg1 charactersIgnoringModifiers:(id)arg2 modifierFlags:(NSUInteger)arg3 focusedAccessibilityElement:(id)arg4 didAppendToPreviousString:(BOOL *)arg5;
- (id)nodeForOrientationChangeWithSymbolName:(id)arg1;
- (id)nodeToFindElementForSnapshots:(id)arg1;
- (id)performWithKeyModifiersAndBlockNodeForModifierFlags:(NSUInteger)arg1;
- (id)remoteNodeWithButtonSymbolName:(id)arg1;
- (id)simpleGestureNodeForMethodName:(id)arg1;
- (id)snapshotInTreeStartingWithSnapshot:(id)arg1 forElement:(id)arg2;
- (id)snapshotsForAccessibilityElement:(id)arg1 applicationSnapshot:(id)arg2;
- (id)stringForKeyModifierFlags:(NSUInteger)arg1;
- (id)typeKeyNodeForKey:(id)arg1 modifierFlags:(NSUInteger)arg2;
- (id)typeStringNodeForString:(id)arg1;

@end

