// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class CLLocation, XCDeviceEvent;

@protocol XCUIDeviceEventAndStateInterface <NSObject>
- (void)clearSimulatedLocationWithReply:(void (^)(BOOL, NSError *))arg1;
- (void)getAppearanceModeWithReply:(void (^)(NSInteger, NSError *))arg1;
- (void)getDeviceOrientationWithCompletion:(void (^)(NSInteger, NSError *))arg1;
- (void)getInterfaceOrientationWithReply:(void (^)(NSInteger, NSError *))arg1;
- (void)getSimulatedLocationWithReply:(void (^)(CLLocation *, NSError *))arg1;
- (void)hasHardwareButton:(NSInteger)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)performDeviceEvent:(XCDeviceEvent *)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)setSimulatedLocation:(CLLocation *)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)updateAppearanceMode:(NSInteger)arg1 completion:(void (^)(BOOL, NSError *))arg2;
- (void)updateDeviceOrientation:(NSInteger)arg1 completion:(void (^)(BOOL, NSError *))arg2;
@end

