// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class XCUIPoint, XCUIRect;

@protocol XCUIElementSnapshotCoordinateTransforms
- (XCUIPoint *)hostingAndOrientationTransformedPoint:(CGPoint)arg1 error:(id *)arg2;
- (XCUIRect *)hostingAndOrientationTransformedRect:(CGRect)arg1 error:(id *)arg2;
- (XCUIPoint *)point:(CGPoint)arg1 transformedForEventSynthesisFromOrientation:(NSInteger)arg2 error:(id *)arg3;
- (XCUIRect *)userOrientationTransformedEventSynthesisRect:(CGRect)arg1 error:(id *)arg2;
@end

