source "https://rubygems.org"

gem "calabash-cucumber"
gem "run_loop", :github => "sergey-plevako-badoo/run_loop", :branch => "add_setting_server_port"
gem "cucumber", "2.99.0"
gem "json", "1.8.6"
gem "rspec", "~> 3.0"
gem "pry"
gem "pry-nav"
