source "https://rubygems.org"

gem "run_loop", :github => "calabash/run_loop", :branch => "feature/device-agent-http-client"
gem "cucumber", "~> 2.0"
gem "slowhandcuke"
gem "rspec", "~> 3.0"
gem "pry"
gem "pry-nav"

