source "https://rubygems.org"

gem "calabash-cucumber"
gem "run_loop", :github => "calabash/run_loop", :branch => "v-malob/xcode-10-3"
gem "cucumber", "2.99.0"
gem "json", "1.8.6"
gem "rspec", "~> 3.0"
gem "pry"
gem "pry-nav"
