// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTMessagingChannel_DaemonToRunner-Protocol.h"

__attribute__((visibility("hidden")))
@interface _XCTRunnerDaemonSessionDummyExportedObject : NSObject <XCTMessagingChannel_DaemonToRunner>
{
}

- (void)_XCT_applicationDidUpdateState:(id)arg1;
- (void)_XCT_applicationWithBundleID:(id)arg1 didUpdatePID:(NSInteger)arg2 andState:(NSUInteger)arg3;
- (void)_XCT_deviceOrientationDidChange:(NSInteger)arg1;
- (void)_XCT_interfaceOrientationDidChange:(NSInteger)arg1;
- (void)_XCT_receivedAccessibilityNotification:(NSInteger)arg1 fromElement:(id)arg2 payload:(id)arg3;
- (void)_XCT_receivedAccessibilityNotification:(NSInteger)arg1 withPayload:(id)arg2;
- (void)_XCT_receivedSignpost:(id)arg1 withToken:(id)arg2;

@end

