// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "_XCTTestIdentifier_Double.h"

__attribute__((visibility("hidden")))
@interface _XCTTestIdentifier_Method_LegacyEncoding : _XCTTestIdentifier_Double
{
}

- (BOOL)encodingShouldIncludeLegacyKeys;

@end

