// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTestObservation-Protocol.h"

@class NSString, XCActivityRecord, XCTContext, XCTSourceCodeContext, XCTestCase;

@protocol _XCTestObservationPrivate <XCTestObservation>

@optional
- (void)_context:(XCTContext *)arg1 didFinishActivity:(XCActivityRecord *)arg2;
- (void)_context:(XCTContext *)arg1 willStartActivity:(XCActivityRecord *)arg2;
- (void)testCase:(XCTestCase *)arg1 didRecordSkipWithDescription:(NSString *)arg2 sourceCodeContext:(XCTSourceCodeContext *)arg3;
@end

