// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSSet;

__attribute__((visibility("hidden")))
@interface _XCTTestIdentifierSet_Set
{
    NSSet *_testIdentifiers;
}

- (id)anyTestIdentifier;
- (BOOL)containsTestIdentifier:(id)arg1;
- (BOOL)containsTestIdentifier:(id)arg1 includingParents:(BOOL)arg2;
- (NSUInteger)count;
- (NSUInteger)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(NSUInteger)arg3;
- (id)initWithTestIdentifiers:(const id *)arg1 count:(NSUInteger)arg2;

@end

