// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSUUID;

@interface XCTAttachmentFuture
{
    NSUUID *_UUID;
    NSUUID *_deviceIdentifier;
}

@property(readonly, nonatomic) NSUUID *UUID;
@property(readonly, nonatomic) NSUUID *deviceIdentifier;

- (id)initWithAttachmentFutureMetadata:(id)arg1 name:(id)arg2 deviceIdentifier:(id)arg3;
- (id)initWithUniformTypeIdentifier:(id)arg1 name:(id)arg2 UUID:(id)arg3 deviceIdentifier:(id)arg4;

@end

