// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray, NSMutableDictionary;

@interface XCTActivityRecordStack : NSObject
{
    NSMutableArray *_storage;
    NSMutableDictionary *_mutableAggregationRecords;
}

@property(readonly) NSDictionary *aggregationRecords;
@property(readonly) NSMutableDictionary *mutableAggregationRecords;
@property(readonly) NSMutableArray *storage;

- (NSInteger)depth;
- (void)didFinishActivity:(id)arg1 observationCenter:(id)arg2 context:(id)arg3;
- (id)topActivity;
- (void)unwindRemainingActivitiesWithObservationCenter:(id)arg1 context:(id)arg2;
- (id)willStartActivityWithTitle:(id)arg1 type:(id)arg2 observationCenter:(id)arg3 context:(id)arg4;

@end

