// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTestExpectationDelegate-Protocol.h"

@class NSArray, NSString;

@interface XCTCompoundExpectation <XCTestExpectationDelegate>
{
    NSUInteger _logicalType;
    NSArray *_subexpectations;
}

@property(readonly) NSUInteger logicalType;
@property(readonly, copy) NSArray *subexpectations;

- (BOOL)_queue_validateSubexpectationsFulfillment;
- (void)_updateFulfilledState;
- (void)cleanup:(BOOL)arg1;
- (void)didFulfillExpectation:(id)arg1;
- (id)initWithLogicalType:(NSUInteger)arg1 subexpectations:(id)arg2;


@end

