// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCDebugLogDelegate-Protocol.h"
#import "XCTASDebugLogDelegate-Protocol.h"

@class NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface XCTDefaultDebugLogHandler : NSObject <XCTASDebugLogDelegate, XCDebugLogDelegate>
{
    NSMutableArray *_logSinks;
    NSMutableArray *_debugMessageBuffer;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(readonly) NSMutableArray *debugMessageBuffer;
@property(readonly) NSObject<OS_dispatch_queue> *queue;

+ (id)sharedHandler;
- (void)_queue_flushDebugMessageBufferWithBlock:(CDUnknownBlockType)arg1;
- (void)addLogSink:(id)arg1;
- (void)logDebugMessage:(id)arg1;
- (void)logStartupInfo;
- (void)printBufferedDebugMessages;
- (void)removeLogSink:(id)arg1;


@end

