// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTTelemetryLogging-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol OS_dispatch_group;

@interface XCTDaemonTelemetryLogger : NSObject <XCTTelemetryLogging>
{
    BOOL _isUITest;
    CDUnknownBlockType _eventDataSink;
    NSString *_sessionUUID;
    NSString *_osVersion;
    NSString *_hardwareModel;
    NSString *_frameworkVariant;
    NSString *_frameworkVersion;
    NSMutableDictionary *_localEvents;
    NSObject<OS_dispatch_group> *_submissionGroup;
}

- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (id)initWithEventDataSink:(CDUnknownBlockType)arg1;
- (id)initWithRunnerDaemonSession:(id)arg1;
- (id)initWithSessionUUID:(id)arg1 OSVersion:(id)arg2 hardwareModel:(id)arg3 frameworkVariant:(id)arg4 frameworkVersion:(id)arg5 isUITest:(BOOL)arg6 eventDataSink:(CDUnknownBlockType)arg7;
- (void)logAnalyticsForCompletionOfTestIdentifier:(id)arg1;
- (void)logCompletionOfTestIdentifier:(id)arg1;
- (void)logEventWithName:(id)arg1;
- (void)logUsageOfClass:(id)arg1 method:(id)arg2;
- (void)logUsageOfFunction:(id)arg1;



@end

