// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@interface XCTExpectedFailureOptions : NSObject <NSCopying>
{
    BOOL _enabled;
    BOOL _strict;
    BOOL _matchesNestedUnmatchedExpectedFailures;
    BOOL _restrictsMatchesToSameThread;
    CDUnknownBlockType _issueMatcher;
}

@property(getter=isEnabled) BOOL enabled;
@property(getter=isStrict) BOOL strict;
@property(copy) CDUnknownBlockType issueMatcher;
@property BOOL matchesNestedUnmatchedExpectedFailures;
@property BOOL restrictsMatchesToSameThread;

+ (id)forNondeterministicTestFailure;
+ (id)nonStrictOptions;

@end

