// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSArray, NSLock, NSMutableArray, NSString;
@protocol XCTestExpectationDelegate;


@protocol XCTestExpectationDelegate;

@interface XCTestExpectation : NSObject
{
    struct atomic_flag {
        _Atomic bool _Value;
    } _hasCleanedUp;
    NSLock *_cleanupHandlersLock;
    NSMutableArray *_cleanupHandlers;
    BOOL _fulfilled;
    BOOL _hasBeenWaitedOn;
    BOOL _inverted;
    BOOL _assertForOverFulfill;
    id <XCTestExpectationDelegate> _delegate;
    NSUInteger _fulfillmentToken;
    NSArray *_fulfillCallStackReturnAddresses;
    NSString *_expectationDescription;
    NSUInteger _expectedFulfillmentCount;
    NSUInteger _numberOfFulfillments;
    NSUInteger _creationToken;
    NSArray *_creationCallStackReturnAddresses;
}

@property(copy, setter=_setExpectationDescription:) NSString *_expectationDescription;
@property(nonatomic) BOOL assertForOverFulfill;
@property(readonly, copy) NSArray *creationCallStackReturnAddresses;
@property(readonly) NSUInteger creationToken;
@property __weak id <XCTestExpectationDelegate> delegate;
@property(copy) NSString *expectationDescription;
@property(nonatomic) NSUInteger expectedFulfillmentCount;
@property(readonly, copy) NSArray *fulfillCallStackReturnAddresses;
@property(readonly) BOOL fulfilled;
@property(nonatomic) NSUInteger fulfillmentCount;
@property(readonly) NSUInteger fulfillmentToken;
@property(readonly) BOOL hasBeenWaitedOn;
@property BOOL hasInverseBehavior;
@property(getter=isInverted) BOOL inverted;
@property NSUInteger numberOfFulfillments;

+ (id)compoundAndExpectationWithSubexpectations:(id)arg1;
+ (id)compoundOrExpectationWithSubexpectations:(id)arg1;
+ (id)expectationWithDescription:(id)arg1;
- (id)_generateExpectationDescription;
- (void)addCleanupHandler:(CDUnknownBlockType)arg1;
- (void)cleanup:(BOOL)arg1;
- (void)fulfill;
- (id)initWithDescription:(id)arg1;
- (void)setHasBeenWaitedOn:(BOOL)arg1 wait:(id)arg2;

@end

