// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTest.h"

@class NSString, XCTTestIdentifier;

@interface XCTestCasePlaceholder : XCTest
{
    XCTTestIdentifier *_identifier;
    NSString *_reason;
}

@property(readonly, copy) NSString *reason;

- (Class)_requiredTestRunBaseClass;
- (id)_xctTestIdentifier;
- (NSInteger)defaultExecutionOrderCompare:(id)arg1;
- (id)initWithIdentifier:(id)arg1 reason:(id)arg2;
- (id)name;
- (id)nameForLegacyLogging;
- (void)performTest:(id)arg1;
- (NSUInteger)testCaseCount;
- (Class)testRunClass;

@end

