// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSArray, NSDictionary, NSNumber, NSSet, NSString, NSURL, NSUUID, XCTAggregateSuiteRunStatistics, XCTCapabilities, XCTRepetitionPolicy, XCTRuntimeIssueDetectionPolicy, XCTScreenCapturePolicy, XCTTestIdentifierSet;

@interface XCTestConfiguration : NSObject <NSSecureCoding, NSCopying>
{
    BOOL _reportResultsToIDE;
    BOOL _testsDrivenByIDE;
    BOOL _disablePerformanceMetrics;
    BOOL _treatMissingBaselinesAsFailures;
    BOOL _reportActivities;
    BOOL _testsMustRunOnMainThread;
    BOOL _initializeForUITesting;
    BOOL _initializeForMultiDevice;
    BOOL _shouldExtractMultiDeviceRequirements;
    BOOL _gatherLocalizableStringsData;
    BOOL _emitOSLogs;
    BOOL _testTimeoutsEnabled;
    NSString *_testBundleRelativePath;
    NSURL *_testBundleURL;
    XCTTestIdentifierSet *_testsToRun;
    XCTTestIdentifierSet *_testsToSkip;
    NSArray *_testTagsToRun;
    NSArray *_testTagsToSkip;
    NSUUID *_sessionIdentifier;
    NSURL *_baselineFileURL;
    NSString *_baselineFileRelativePath;
    NSString *_targetApplicationPath;
    NSString *_targetApplicationBundleID;
    NSDictionary *_testApplicationDependencies;
    NSSet *_bundleIDsForCrashReportEmphasis;
    NSDictionary *_testApplicationUserOverrides;
    NSString *_productModuleName;
    NSString *_multiDeviceRequirementsFilePath;
    NSNumber *_traceCollectionEnabled;
    NSDictionary *_performanceTestConfiguration;
    NSNumber *_enablePerformanceTestsDiagnostics;
    NSDictionary *_targetApplicationEnvironment;
    NSArray *_targetApplicationArguments;
    XCTAggregateSuiteRunStatistics *_aggregateStatisticsBeforeCrash;
    NSString *_automationFrameworkPath;
    NSInteger _systemAttachmentLifetime;
    NSInteger _userAttachmentLifetime;
    NSInteger _preferredScreenCaptureFormat;
    NSInteger _testExecutionOrdering;
    NSNumber *_randomExecutionOrderingSeed;
    XCTRepetitionPolicy *_repetitionPolicy;
    XCTRuntimeIssueDetectionPolicy *_runtimeIssueDetectionPolicy;
    NSInteger _leaksCheckingMode;
    NSNumber *_defaultTestExecutionTimeAllowance;
    NSNumber *_maximumTestExecutionTimeAllowance;
    CDUnknownBlockType _randomNumberGenerator;
    NSString *_basePathForTestBundleResolution;
    XCTCapabilities *_IDECapabilities;
    NSDictionary *_applicationBundleInfos;
    NSDictionary *_multiDevicePlatformVersionMap;
}

@property(retain) XCTCapabilities *IDECapabilities;
@property(copy) XCTAggregateSuiteRunStatistics *aggregateStatisticsBeforeCrash;
@property(copy) NSDictionary *applicationBundleInfos;
@property(copy) NSString *automationFrameworkPath;
@property(copy, nonatomic) NSString *basePathForTestBundleResolution;
@property(copy) NSString *baselineFileRelativePath;
@property(copy, nonatomic) NSURL *baselineFileURL;
@property(copy) NSSet *bundleIDsForCrashReportEmphasis;
@property(copy, nonatomic) NSNumber *defaultTestExecutionTimeAllowance;
@property BOOL disablePerformanceMetrics;
@property(readonly) XCTScreenCapturePolicy *effectiveScreenCapturePolicy;
@property BOOL emitOSLogs;
@property(copy) NSNumber *enablePerformanceTestsDiagnostics;
@property BOOL gatherLocalizableStringsData;
@property BOOL initializeForMultiDevice;
@property BOOL initializeForUITesting;
@property NSInteger leaksCheckingMode;
@property(copy, nonatomic) NSNumber *maximumTestExecutionTimeAllowance;
@property(copy) NSDictionary *multiDevicePlatformVersionMap;
@property(copy) NSString *multiDeviceRequirementsFilePath;
@property(copy) NSDictionary *performanceTestConfiguration;
@property(nonatomic) NSInteger preferredScreenCaptureFormat;
@property(copy) NSString *productModuleName;
@property(retain) NSNumber *randomExecutionOrderingSeed;
@property(copy) CDUnknownBlockType randomNumberGenerator;
@property(retain) XCTRepetitionPolicy *repetitionPolicy;
@property BOOL reportActivities;
@property BOOL reportResultsToIDE;
@property(retain) XCTRuntimeIssueDetectionPolicy *runtimeIssueDetectionPolicy;
@property(copy) NSUUID *sessionIdentifier;
@property BOOL shouldExtractMultiDeviceRequirements;
@property NSInteger systemAttachmentLifetime;
@property(copy) NSArray *targetApplicationArguments;
@property(copy) NSString *targetApplicationBundleID;
@property(copy) NSDictionary *targetApplicationEnvironment;
@property(copy) NSString *targetApplicationPath;
@property(copy) NSDictionary *testApplicationDependencies;
@property(copy) NSDictionary *testApplicationUserOverrides;
@property(copy) NSString *testBundleRelativePath;
@property(copy, nonatomic) NSURL *testBundleURL;
@property NSInteger testExecutionOrdering;
@property(copy) NSArray *testTagsToRun;
@property(copy) NSArray *testTagsToSkip;
@property BOOL testTimeoutsEnabled;
@property BOOL testsDrivenByIDE;
@property BOOL testsMustRunOnMainThread;
@property(copy) XCTTestIdentifierSet *testsToRun;
@property(copy) XCTTestIdentifierSet *testsToSkip;
@property(copy) NSNumber *traceCollectionEnabled;
@property BOOL treatMissingBaselinesAsFailures;
@property NSInteger userAttachmentLifetime;
@property(readonly, copy) NSString *testBundleName;
@property(readonly) NSInteger testMode;

+ (id)activeTestConfiguration;
+ (id)defaultBasePathForTestBundleResolution;
+ (id)defaultBasePathForTestBundleResolutionForMainBundlePath:(id)arg1;
+ (void)setActiveTestConfiguration:(id)arg1;
- (void)clearXcodeReportingConfiguration;

@end

