// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, XCTTestIdentifier;

@interface XCTestCasePlaceholder
{
    XCTTestIdentifier *_identifier;
    NSString *_reason;
}

@property(readonly, copy) NSString *reason;

- (Class)_requiredTestRunBaseClass;
- (id)_xctTestIdentifier;
- (NSInteger)defaultExecutionOrderCompare:(id)arg1;
- (id)initWithIdentifier:(id)arg1 reason:(id)arg2;
- (id)name;
- (id)nameForLegacyLogging;
- (void)performTest:(id)arg1;
- (NSUInteger)testCaseCount;
- (Class)testRunClass;

@end

