// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTTestWorker-Protocol.h"

@class NSArray, NSError, NSString, XCTBlockingQueue;

__attribute__((visibility("hidden")))
@interface XCTExecutionWorker : NSObject <XCTTestWorker>
{
    BOOL _result;
    XCTBlockingQueue *_workQueue;
    NSError *_error;
    NSArray *_executionExtensions;
}

- (void)enqueueTestIdentifiersToRun:(id)arg1 testIdentifiersToSkip:(id)arg2;
- (void)executeTestIdentifiers:(id)arg1 skippingTestIdentifiers:(id)arg2 completionHandler:(CDUnknownBlockType)arg3 completionQueue:(id)arg4;
- (void)fetchDiscoveredTestClasses:(CDUnknownBlockType)arg1;
- (id)initWithExecutionExtensions:(id)arg1;
- (BOOL)runWithError:(id *)arg1;
- (void)shutdown;


@end

