// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSArray, NSDate, NSError, NSString, XCTSourceCodeContext;

@interface XCTIssue : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>
{
    struct atomic_flag *_failureBreakPointCalled;
    BOOL _isExpectedFailure;
    BOOL _didInterruptTest;
    BOOL _shouldInterruptTest;
    NSInteger _type;
    NSString *_compactDescription;
    NSString *_detailedDescription;
    XCTSourceCodeContext *_sourceCodeContext;
    NSError *_associatedError;
    NSArray *_attachments;
    NSDate *_timestamp;
    NSInteger _runtimeIssueSeverity;
    NSUInteger _threadId;
    NSString *_expectedFailureReason;
}

@property(retain) NSError *associatedError;
@property(copy) NSArray *attachments;
@property(copy) NSString *compactDescription;
@property(copy) NSString *detailedDescription;
@property BOOL didInterruptTest;
@property(copy) NSString *expectedFailureReason;
@property struct atomic_flag failureBreakPointCalled;
@property BOOL isExpectedFailure;
@property(readonly) BOOL isLegacyExpectedFailure;
@property NSInteger runtimeIssueSeverity;
@property BOOL shouldInterruptTest;
@property(retain) XCTSourceCodeContext *sourceCodeContext;
@property NSUInteger threadId;
@property(copy) NSDate *timestamp;
@property NSInteger type;

+ (id)issueWithException:(id)arg1;
+ (id)issueWithExceptionPointer:(id)arg1;
+ (id)issueWithType:(NSInteger)arg1 compactDescription:(id)arg2 associatedError:(id)arg3;
+ (id)issueWithType:(NSInteger)arg1 compactDescription:(id)arg2 callStackAddresses:(id)arg3 filePath:(id)arg4 lineNumber:(NSInteger)arg5;
- (void)_updateAttachmentsTimestamps;
- (id)initWithType:(NSInteger)arg1 compactDescription:(id)arg2;
- (id)initWithType:(NSInteger)arg1 compactDescription:(id)arg2 detailedDescription:(id)arg3 sourceCodeContext:(id)arg4 associatedError:(id)arg5 attachments:(id)arg6;
- (BOOL)isFailure;
- (BOOL)matchesLegacyPropertiesOfIssue:(id)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (void)replaceAttachment:(id)arg1 withAttachment:(id)arg2;

@end

