// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@interface XCTKVOExpectation
{
    NSString *_keyPath;
    id _observedObject;
    id _expectedValue;
    NSUInteger _options;
    CDUnknownBlockType _handler;
}

@property(readonly) id expectedValue;
@property(copy) CDUnknownBlockType handler;
@property(readonly, copy) NSString *keyPath;
@property(readonly) id observedObject;
@property(readonly) NSUInteger options;

- (id)_generateExpectationDescription;
- (void)cleanup:(BOOL)arg1;
- (id)initWithKeyPath:(id)arg1 object:(id)arg2;
- (id)initWithKeyPath:(id)arg1 object:(id)arg2 expectedValue:(id)arg3;
- (id)initWithKeyPath:(id)arg1 object:(id)arg2 expectedValue:(id)arg3 options:(NSUInteger)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

