// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTestExpectation.h"

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface XCTKVOExpectation : XCTestExpectation
{
    BOOL _hasCleanedUp;
    CDUnknownBlockType _handler;
    NSString *_keyPath;
    id _observedObject;
    id _expectedValue;
    NSUInteger _options;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(readonly) id expectedValue;
@property(copy) CDUnknownBlockType handler;
@property BOOL hasCleanedUp;
@property(readonly, copy) NSString *keyPath;
@property(readonly) id observedObject;
@property(readonly) NSUInteger options;
@property(readonly) NSObject<OS_dispatch_queue> *queue;

- (void)cleanup;
- (id)initWithKeyPath:(id)arg1 object:(id)arg2;
- (id)initWithKeyPath:(id)arg1 object:(id)arg2 expectedValue:(id)arg3;
- (id)initWithKeyPath:(id)arg1 object:(id)arg2 expectedValue:(id)arg3 options:(NSUInteger)arg4;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;

@end

