// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSData, NSNumber, NSString;

@interface XCTMemgraph : NSObject <NSCopying, NSSecureCoding>
{
    NSNumber *_leakNodesCount;
    NSNumber *_leakNodesBytes;
    NSInteger _processIdentifier;
    NSString *_filePath;
    NSData *_graphData;
}

@property(readonly, nonatomic) NSString *filePath;
@property(readonly, nonatomic) NSData *graphData;
@property(readonly, nonatomic) NSUInteger leakNodesBytes;
@property(readonly, nonatomic) NSUInteger leakNodesCount;
@property(readonly, nonatomic) NSInteger processIdentifier;

- (void)computeLeakProperties;
- (id)initWithGraphData:(id)arg1;
- (id)initWithPid:(NSInteger)arg1 filePath:(id)arg2;
- (id)saveMemgraphData:(id)arg1 withProcessName:(id)arg2;

@end

