// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, XCDeviceEvent, XCSynthesizedEventRecord;

@protocol XCTMessagingRole_EventSynthesis
- (void)_XCT_enableFauxCollectionViewCells:(void (^)(BOOL, NSError *))arg1;
- (void)_XCT_getDeviceOrientationWithCompletion:(void (^)(NSNumber *, NSError *))arg1;
- (void)_XCT_loadAccessibilityWithTimeout:(double)arg1 reply:(void (^)(BOOL, NSError *))arg2;
- (void)_XCT_performDeviceEvent:(XCDeviceEvent *)arg1 completion:(void (^)(NSError *))arg2;
- (void)_XCT_sendString:(NSString *)arg1 maximumFrequency:(NSUInteger)arg2 completion:(void (^)(NSError *))arg3;
- (void)_XCT_setAXTimeout:(double)arg1 reply:(void (^)(NSInteger))arg2;
- (void)_XCT_setLocalizableStringsDataGatheringEnabled:(BOOL)arg1 reply:(void (^)(BOOL, NSError *))arg2;
- (void)_XCT_synthesizeEvent:(XCSynthesizedEventRecord *)arg1 completion:(void (^)(NSError *))arg2;
- (void)_XCT_unloadAccessibility:(void (^)(BOOL, NSError *))arg1;
- (void)_XCT_updateDeviceOrientation:(NSInteger)arg1 completion:(void (^)(NSError *))arg2;
@end

