// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol XCTMessagingRole_SystemConfiguration
- (void)_XCT_getAppearanceModeWithReply:(void (^)(NSInteger, NSError *))arg1;
- (void)_XCT_updateAppearanceMode:(NSInteger)arg1 completion:(void (^)(NSError *))arg2;
@end

