// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSNotificationCenter, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface XCTNSNotificationExpectation
{
    CDUnknownBlockType _handler;
    NSString *_notificationName;
    id _observedObject;
    NSNotificationCenter *_notificationCenter;
    NSObject<OS_dispatch_queue> *_queue;
}

@property(copy) CDUnknownBlockType handler;
@property(readonly) NSNotificationCenter *notificationCenter;
@property(readonly, copy) NSString *notificationName;
@property(readonly) id observedObject;
@property(readonly) NSObject<OS_dispatch_queue> *queue;

- (void)_observeExpectedNotification:(id)arg1;
- (void)cleanup:(BOOL)arg1;
- (id)initWithName:(id)arg1;
- (id)initWithName:(id)arg1 object:(id)arg2;
- (id)initWithName:(id)arg1 object:(id)arg2 notificationCenter:(id)arg3;

@end

