// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import "XCTestExpectation.h"

@class NSObject, NSPredicate, NSRunLoop, NSString, NSTimer;
@protocol OS_dispatch_queue;

@interface XCTNSPredicateExpectation : XCTestExpectation
{
    BOOL _hasCleanedUp;
    BOOL _isEvaluating;
    BOOL _shouldEvaluate;
    CDUnknownBlockType _handler;
    NSString *_debugDescription;
    NSPredicate *_predicate;
    id _object;
    NSObject<OS_dispatch_queue> *_queue;
    NSRunLoop *_timerRunLoop;
    NSTimer *_timer;
    double _pollingInterval;
}

@property(copy) NSString *debugDescription;
@property(copy) CDUnknownBlockType handler;
@property BOOL hasCleanedUp;
@property BOOL isEvaluating;
@property(readonly) id object;
@property double pollingInterval;
@property(readonly, copy) NSPredicate *predicate;
@property(readonly) NSObject<OS_dispatch_queue> *queue;
@property BOOL shouldEvaluate;
@property(retain) NSTimer *timer;
@property(retain) NSRunLoop *timerRunLoop;
@property(nonatomic) NSUInteger expectedFulfillmentCount; // @dynamic expectedFulfillmentCount;

- (void)_considerFulfilling;
- (void)_scheduleTimer;
- (BOOL)_shouldFulfillForObject:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)cleanup;
- (void)fulfill;
- (id)initWithPredicate:(id)arg1 object:(id)arg2;
- (void)on_queue_setHasBeenWaitedOn:(BOOL)arg1;
- (void)startPolling;


@end

