// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTSymbolInfoProviding-Protocol.h"

@class NSArray, NSString;

@interface XCTOutOfProcessSymbolicationService : NSObject <XCTSymbolInfoProviding>
{
    BOOL _releaseOnDealloc;
    NSArray *_symbolicators;
    CDStruct_37ea9563 _symbolicationFunctions;
}

@property(readonly) BOOL releaseOnDealloc;
@property(copy) NSArray *symbolicators;
@property(readonly) CDStruct_37ea9563 symbolicationFunctions;

+ (id)recursivelyFindDSYMsInDirectory:(id)arg1;
- (id)initWithDSYMURLs:(id)arg1 includeSharedCache:(BOOL)arg2 skipMalformedDSYMs:(BOOL)arg3 skippedDSYMURLs:(id *)arg4 error:(id *)arg5;
- (id)initWithDSYMURLs:(id)arg1 includeSharedCache:(BOOL)arg2 symbolicationFunctions:(CDStruct_37ea9563)arg3 skipMalformedDSYMs:(BOOL)arg4 skippedDSYMURLs:(id *)arg5 error:(id *)arg6;
- (id)initWithSymbolicators:(id)arg1 releaseOnDealloc:(BOOL)arg2 symbolicationFunctions:(CDStruct_37ea9563)arg3;
- (id)symbolInfoForAddressInCurrentProcess:(NSUInteger)arg1 error:(id *)arg2;
- (id)symbolInfoForImageOffset:(NSUInteger)arg1 forImageWithPath:(id)arg2 andArch:(id)arg3 error:(id *)arg4;
- (id)symbolInfoForImageOffset:(NSUInteger)arg1 inImageWithUUID:(id)arg2 error:(id *)arg3;


@end

