// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSData, NSString, NSXPCConnection, XCAccessibilityElement;
@protocol XCUIAXNotificationHandling, XCUIApplicationPlatformServicesProviderDelegate;

@protocol XCTRunnerDaemonSessionUIAutomationDelegate <NSObject>

@optional
+ (void)registerCapabilitiesForDaemonConnection:(NSXPCConnection *)arg1 completion:(void (^)(XCTCapabilities *, NSError *))arg2;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"<XCUIAXNotificationHandling>",?,W

- (void)daemonDidUpdatePID:(NSInteger)arg1 forApplicationWithBundleID:(NSString *)arg2 andState:(NSUInteger)arg3;
- (void)finishInitializationForUIAutomation;
// Preceding property had unknown attributes: ?
// Original attribute string: T@"<XCUIApplicationPlatformServicesProviderDelegate>",?,W

- (void)receivedAccessibilityNotification:(NSInteger)arg1 fromElement:(XCAccessibilityElement *)arg2 payload:(NSData *)arg3;
- (void)requestBackgroundAssertionForPID:(NSInteger)arg1 reply:(void (^)(BOOL))arg2;
// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,R

// Preceding property had unknown attributes: ?
// Original attribute string: TB,?,R

@end

