// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@interface XCTRepetitionPolicy : NSObject <NSSecureCoding>
{
    BOOL _repeatInNewRunnerProcess;
    BOOL _isDefault;
    NSInteger _mode;
    NSInteger _maximumIterations;
}

@property(readonly) BOOL isDefault;
@property(readonly) NSInteger maximumIterations;
@property(readonly) NSInteger mode;
@property(readonly) BOOL repeatInNewRunnerProcess;

+ (id)defaultRepetitionPolicy;
+ (NSInteger)modeFromString:(id)arg1;
+ (id)stringFromRepetitionMode:(NSInteger)arg1;
- (id)dictionaryRepresentation;
- (id)initRetryOnFailureWithMaximumIterations:(NSInteger)arg1 repeatInNewRunnerProcess:(BOOL)arg2;
- (id)initUntilFailureWithMaximumIterations:(NSInteger)arg1 repeatInNewRunnerProcess:(BOOL)arg2;
- (id)initWithDictionary:(id)arg1;
- (id)initWithFixedIterations:(NSInteger)arg1 repeatInNewRunnerProcess:(BOOL)arg2;
- (id)initWithRepetitionMode:(NSInteger)arg1 maximumIterations:(NSInteger)arg2 repeatInNewRunnerProcess:(BOOL)arg3;
- (BOOL)shouldRepeatWithTestFailure:(BOOL)arg1 iteration:(NSInteger)arg2;

@end

