// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSString, XCTSourceCodeLocation;

@interface XCTSourceCodeSymbolInfo : NSObject <NSSecureCoding>
{
    NSString *_imageName;
    NSString *_symbolName;
    XCTSourceCodeLocation *_location;
}

@property(readonly, copy) NSString *imageName;
@property(readonly) XCTSourceCodeLocation *location;
@property(readonly, copy) NSString *symbolName;

- (id)initWithImageName:(id)arg1 symbolName:(id)arg2 location:(id)arg3;

@end

