// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//


#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

@class NSString, XCTSourceCodeSymbolInfo;

@protocol XCTSymbolInfoProviding <NSObject>
- (XCTSourceCodeSymbolInfo *)symbolInfoForAddressInCurrentProcess:(NSUInteger)arg1 error:(id *)arg2;
- (XCTSourceCodeSymbolInfo *)symbolInfoForImageOffset:(NSUInteger)arg1 forImageWithPath:(NSString *)arg2 andArch:(NSString *)arg3 error:(id *)arg4;
- (XCTSourceCodeSymbolInfo *)symbolInfoForImageOffset:(NSUInteger)arg1 inImageWithUUID:(NSString *)arg2 error:(id *)arg3;
@end

