// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTTelemetryLogging-Protocol.h"

@class NSArray, NSString;

@interface XCTTelemetryLogger : NSObject <XCTTelemetryLogging>
{
    NSArray *_loggers;
}

@property(readonly, copy) NSArray *loggers;

+ (double)defaultFlushTimeout;
+ (id)defaultLoggersWithRunnerDaemonSession:(id)arg1;
+ (void)setSharedLogger:(id)arg1;
+ (id)sharedLogger;
+ (id)sharedLoggerIfInitiated;
- (void)flushWithCompletion:(CDUnknownBlockType)arg1;
- (void)flushWithTimeout:(double)arg1;
- (id)initWithLoggers:(id)arg1;
- (id)initWithRunnerDaemonSession:(id)arg1;
- (void)logCompletionOfTestIdentifier:(id)arg1;
- (void)logEventWithName:(id)arg1;
- (void)logUsageOfClass:(id)arg1 method:(id)arg2;
- (void)logUsageOfFunction:(id)arg1;



@end

