// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

@class NSInvocation, NSNumber, NSString;

@interface XCTTestInvocationDescriptor : NSObject
{
    NSString *_selectorString;
    NSNumber *_convention;
    NSInvocation *_invocation;
    NSString *_customErrorMessage;
}

@property(readonly) NSNumber *convention;
@property(readonly, copy) NSString *customErrorMessage;
@property(readonly) NSInvocation *invocation;
@property(readonly, getter=isAvailable) BOOL available;
@property(readonly, copy) NSString *selectorString;

- (id)initWithSelectorString:(id)arg1 convention:(NSInteger)arg2 invocation:(id)arg3 customErrorMessage:(id)arg4;
- (id)initWithSelectorString:(id)arg1 conventionNumber:(id)arg2 invocation:(id)arg3 customErrorMessage:(id)arg4;
- (id)initWithSelectorString:(id)arg1 invocation:(id)arg2 customErrorMessage:(id)arg3;

@end

