// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>


@class NSMutableSet, XCTTestIdentifierSet;

@interface XCTTestIdentifierSetBuilder : NSObject <NSCopying>
{
    NSMutableSet *_testIdentifiers;
}

@property(readonly) NSUInteger count;
@property(readonly) XCTTestIdentifierSet *testIdentifierSet;

- (void)addTestIdentifier:(id)arg1;
- (void)addTestIdentifierWithLegacyStringRepresentation:(id)arg1 includingSwiftCounterpart:(BOOL)arg2;
- (id)anyTestIdentifier;
- (BOOL)containsTestIdentifier:(id)arg1;
- (id)initWithArray:(id)arg1;
- (id)initWithSet:(id)arg1;
- (id)initWithTestIdentifier:(id)arg1;
- (id)initWithTestIdentifierSet:(id)arg1;
- (void)minusBuilder:(id)arg1;
- (void)minusSet:(id)arg1;
- (void)removeAllTestIdentifiers;
- (void)removeTestIdentifier:(id)arg1;
- (void)unionBuilder:(id)arg1;
- (void)unionSet:(id)arg1;

@end

