// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTWaiterManagement-Protocol.h"

@class NSArray, NSMutableOrderedSet, NSString, XCTWaiterWait;
@protocol XCTWaiterDelegate, XCTWaiterManager;


@protocol XCTWaiterDelegate;

@interface XCTWaiter : NSObject <XCTWaiterManagement>
{
    NSMutableOrderedSet *_fulfilledExpectations;
    XCTWaiterWait *_lastWait;
    struct __CFRunLoop *_runLoopForPrimitiveWait;
    id <XCTWaiterDelegate> _delegate;
    id <XCTWaiterManager> _customManager;
}

@property __weak id <XCTWaiterManager> customManager;
@property __weak id <XCTWaiterDelegate> delegate;
@property(readonly) NSArray *fulfilledExpectations;

+ (void)setStallHandler:(CDUnknownBlockType)arg1;
+ (void)setWatchdogTimeoutSlop:(double)arg1;
+ (CDUnknownBlockType)stallHandler;
+ (void)wait:(double)arg1;
+ (NSInteger)waitForExpectations:(id)arg1;
+ (NSInteger)waitForExpectations:(id)arg1 enforceOrder:(BOOL)arg2;
+ (NSInteger)waitForExpectations:(id)arg1 timeout:(double)arg2;
+ (NSInteger)waitForExpectations:(id)arg1 timeout:(double)arg2 enforceOrder:(BOOL)arg3;
+ (double)watchdogTimeoutSlop;
- (BOOL)allowsNestedWaitersWithWait:(id)arg1;
- (void)cancelPrimitiveWait;
- (void)cancelWaiting;
- (void)handleStalledWait:(id)arg1;
- (void)handleStalledWait:(id)arg1 after:(double)arg2;
- (id)initWithDelegate:(id)arg1;
- (void)interruptWait:(id)arg1 forWaiter:(id)arg2;
- (void)primitiveWait:(double)arg1;
- (void)swift_waitForExpectations:(id)arg1 timeout:(double)arg2 enforceOrder:(BOOL)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (NSInteger)waitForExpectations:(id)arg1;
- (NSInteger)waitForExpectations:(id)arg1 enforceOrder:(BOOL)arg2;
- (NSInteger)waitForExpectations:(id)arg1 timeout:(double)arg2;
- (NSInteger)waitForExpectations:(id)arg1 timeout:(double)arg2 enforceOrder:(BOOL)arg3;



@end

