// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by classdump-c 4.2.0 (64 bit) (iOS port by DreamDevLost, Updated by Kevin Bradley.)(Debug version compiled May 27 2023 00:50:17).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <XCTest/XCUIElementTypes.h>
#import "CDStructures.h"
@protocol OS_dispatch_queue;
@protocol OS_xpc_object;

#import <objc/NSObject.h>

#import "XCTestExpectationDelegate-Protocol.h"

@class NSArray, NSString;

@interface XCTWaiterWait : NSObject <XCTestExpectationDelegate>
{
    struct __CFRunLoop *_runLoop;
    NSUInteger _result:4;
    NSUInteger _stalled:1;
    BOOL _enforceOrder;
    BOOL _synchronous;
    NSArray *_expectations;
    double _timeout;
    NSArray *_callStackReturnAddressesOfCaller;
    NSUInteger _threadIDOfCaller;
}

- (void)didFulfillExpectation:(id)arg1;
- (id)initWithExpectations:(id)arg1 timeout:(double)arg2 enforceOrder:(BOOL)arg3 isSynchronous:(BOOL)arg4;



@end

