// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May  6 2021 20:43:33).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

typedef void (^CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

#pragma mark Typedef'd Structures

typedef struct {
    NSUInteger _field1;
    NSUInteger *_field2;
    NSUInteger *_field3;
    NSUInteger _field4[5];
} CDStruct_70511ce9;

typedef struct {
    CDUnknownFunctionPointerType symbolicatorCreateWithTask;
    CDUnknownFunctionPointerType symbolicatorGetSymbolOwnerWithAddressAtTime;
    CDUnknownFunctionPointerType symbolOwnerGetName;
    CDUnknownFunctionPointerType symbolOwnerGetSymbolWithAddress;
    CDUnknownFunctionPointerType symbolOwnerGetSourceInfoWithAddress;
    CDUnknownFunctionPointerType symbolGetName;
    CDUnknownFunctionPointerType sourceInfoGetPath;
    CDUnknownFunctionPointerType sourceInfoGetLineNumber;
} CDStruct_7da0dd4a;

typedef struct {
    NSInteger _field1;
    NSInteger _field2;
    NSInteger _field3;
} CDStruct_2ec95fd7;

