// class-dump results processed by bin/class-dump/dump.rb
//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 26 2020 14:08:26).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/Foundation.h>

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Typedef'd Structures

typedef struct {
    NSUInteger _field1;
    id _field2;
    NSUInteger *_field3;
    NSUInteger _field4[5];
} CDStruct_70511ce9;

typedef struct {
    CDUnknownBlockType release;
    CDUnknownBlockType retain;
    CDUnknownBlockType isNull;
    CDUnknownBlockType getArchitectureForName;
    CDUnknownBlockType symbolicatorCreateWithTask;
    CDUnknownBlockType symbolicatorForeachSymbolicatorWithPath;
    CDUnknownBlockType symbolicatorForeachSharedCache;
    CDUnknownBlockType symbolOwnerGetBaseAddress;
    CDUnknownBlockType symbolicatorGetArchitecture;
    CDUnknownBlockType symbolicatorForeachSymbolOwnerWithPathAtTime;
    CDUnknownBlockType symbolicatorGetSymbolOwnerWithUUIDAtTime;
    CDUnknownBlockType symbolicatorGetSymbolOwnerWithAddressAtTime;
    CDUnknownBlockType symbolOwnerGetName;
    CDUnknownBlockType symbolOwnerGetSymbolWithAddress;
    CDUnknownBlockType symbolOwnerGetSourceInfoWithAddress;
    CDUnknownBlockType symbolGetName;
    CDUnknownBlockType sourceInfoGetPath;
    CDUnknownBlockType sourceInfoGetLineNumber;
} CDStruct_37ea9563;

typedef struct {
    NSInteger _field1;
    NSInteger _field2;
    NSInteger _field3;
} CDStruct_2ec95fd7;

typedef struct {
    NSObject *userDispatchQueue;
    id dispatchTarget;
    CDUnknownBlockType messageHandler;
    CDUnknownBlockType dispatchValidator;
} CDStruct_f5f3468d;

